Rusty Bargain used car sales service is developing an app to attract new customers. In that app, you can quickly find out the market value of your car. You have access to historical data: technical specifications, trim versions, and prices. You need to build the model to determine the value. 

Rusty Bargain is interested in:

- the quality of the prediction;
- the speed of the prediction;
- the time required for training

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# 1. Data preparation

### Downloading

In [2]:
data = pd.read_csv('autos.csv')
print(data.shape)
data.head()

(354369, 16)

,DateCrawled,Price,VehicleType,RegistrationYear,Gearbox,Power,Model,Kilometer,RegistrationMonth,FuelType,Brand,NotRepaired,DateCreated,NumberOfPictures,PostalCode,LastSeen
0,2016-03-24 11:52:17,480,NaN,1993,manual,0,golf,150000,0,petrol,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,2016-03-24 10:58:45,18300,coupe,2011,manual,190,NaN,125000,5,gasoline,audi,yes,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,9800,suv,2004,auto,163,grand,125000,8,gasoline,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,1500,small,2001,manual,75,golf,150000,6,petrol,volkswagen,no,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,3600,small,2008,manual,69,fabia,90000,7,gasoline,skoda,no,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21

### Preprocessing

Unnecessary features (can't be used in the product):

- dates
- zip-code

In [3]:
data = data.drop(['DateCrawled', 'DateCreated', 'PostalCode', 'LastSeen'], axis=1)
data.head()

,Price,VehicleType,RegistrationYear,Gearbox,Power,Model,Kilometer,RegistrationMonth,FuelType,Brand,NotRepaired,NumberOfPictures
0,480,NaN,1993,manual,0,golf,150000,0,petrol,volkswagen,NaN,0
1,18300,coupe,2011,manual,190,NaN,125000,5,gasoline,audi,yes,0
2,9800,suv,2004,auto,163,grand,125000,8,gasoline,jeep,NaN,0
3,1500,small,2001,manual,75,golf,150000,6,petrol,volkswagen,no,0
4,3600,small,2008,manual,69,fabia,90000,7,gasoline,skoda,no,0

In [4]:
data['NumberOfPictures'].value_counts()

0    354369
Name: NumberOfPictures, dtype: int64

Deleting constant feature

In [5]:
data = data.drop(['NumberOfPictures'], axis=1)
data.head()

,Price,VehicleType,RegistrationYear,Gearbox,Power,Model,Kilometer,RegistrationMonth,FuelType,Brand,NotRepaired
0,480,NaN,1993,manual,0,golf,150000,0,petrol,volkswagen,NaN
1,18300,coupe,2011,manual,190,NaN,125000,5,gasoline,audi,yes
2,9800,suv,2004,auto,163,grand,125000,8,gasoline,jeep,NaN
3,1500,small,2001,manual,75,golf,150000,6,petrol,volkswagen,no
4,3600,small,2008,manual,69,fabia,90000,7,gasoline,skoda,no

In [6]:
data.describe()

,Price,RegistrationYear,Power,Kilometer,RegistrationMonth
count,354369.000000,354369.000000,354369.000000,354369.000000,354369.000000
mean,4416.656776,2004.234448,110.094337,128211.172535,5.714645
std,4514.158514,90.227958,189.850405,37905.341530,3.726421
min,0.000000,1000.000000,0.000000,5000.000000,0.000000
25%,1050.000000,1999.000000,69.000000,125000.000000,3.000000
50%,2700.000000,2003.000000,105.000000,150000.000000,6.000000
75%,6400.000000,2008.000000,143.000000,150000.000000,9.000000
max,20000.000000,9999.000000,20000.000000,150000.000000,12.000000

The registration year of 1000 and 9999 is clearly incorrect, delete entries with incorrect values.

Power cannot be equal to 0.

In [7]:
data = data[data['RegistrationYear'] < 2050]
data = data[data['RegistrationYear'] > 1900]
data = data[data['Power'] != 0]

data.reset_index()
data.shape

(314100, 11)

In [8]:
data.isna().sum(axis=0)

Price                    0
VehicleType          22818
RegistrationYear         0
Gearbox               6501
Power                    0
Model                13395
Kilometer                0
RegistrationMonth        0
FuelType             21212
Brand                    0
NotRepaired          49708
dtype: int64

Missing values are only in categorical columns. They can be filled with a new value "unknown".

In [9]:
data = data.fillna('unknown')
data.isna().sum(axis=0)

Price                0
VehicleType          0
RegistrationYear     0
Gearbox              0
Power                0
Model                0
Kilometer            0
RegistrationMonth    0
FuelType             0
Brand                0
NotRepaired          0
dtype: int64

### Feature encoding

In [10]:
categorical_features = [
    'VehicleType',
    'Gearbox', 
    'Model',
    'FuelType', 
    'Brand',
    'NotRepaired', 
]

**OHE-encoding**

Here, some features will have to be removed due to the large number of values

In [11]:
for feature in categorical_features:
    print(data[feature].value_counts())

sedan          84852
small          71522
wagon          60508
bus            26530
unknown        22818
convertible    19034
coupe          15078
suv            11115
other           2643
Name: VehicleType, dtype: int64
manual     246097
auto        61502
unknown      6501
Name: Gearbox, dtype: int64
golf                  26760
other                 21248
3er                   18226
unknown               13395
polo                  11455
corsa                 10798
astra                  9698
passat                 9263
a4                     9171
c_klasse               7568
5er                    7369
e_klasse               6147
a3                     5630
focus                  5337
a6                     5178
fiesta                 5048
2_reihe                4494
transporter            4326
twingo                 3998
fortwo                 3914
vectra                 3734
a_klasse               3654
1er                    3391
mondeo                 3168
3_reihe                3148
touran                 3109
clio                   3023
punto                  2828
zafira                 2691
megane                 2511
                      ...
crossfire                58
911                      56
nubira                   55
range_rover_sport        52
move                     46
lybra                    43
v60                      40
croma                    38
145                      38
terios                   32
delta                    31
lodgy                    30
9000                     28
b_max                    25
musa                     23
charade                  21
materia                  17
200                      16
amarok                   15
q3                       14
kappa                    13
gl                       12
elefantino               10
serie_2                   6
kalina                    5
samara                    5
i3                        5
serie_3                   3
rangerover                3
range_rover_evoque        2
Name: Model, Length: 250, dtype: int64
petrol      196358
gasoline     90723
unknown      21212
lpg           4913
cng            506
hybrid         207
other          103
electric        78
Name: FuelType, dtype: int64
volkswagen        68805
opel              34902
bmw               33876
mercedes_benz     28512
audi              27075
ford              21900
renault           14956
peugeot            9816
fiat               8178
seat               6292
skoda              5103
mazda              4977
smart              4657
citroen            4505
nissan             4268
toyota             4160
hyundai            3234
mini               3080
volvo              2937
mitsubishi         2653
honda              2546
kia                2205
alfa_romeo         2090
suzuki             2052
sonstige_autos     1979
chevrolet          1529
chrysler           1239
dacia               829
subaru              682
daihatsu            658
porsche             645
jeep                601
saab                493
land_rover          476
jaguar              448
daewoo              434
lancia              414
rover               404
trabant             327
lada                163
Name: Brand, dtype: int64
no         233116
unknown     49708
yes         31276
Name: NotRepaired, dtype: int64

In [12]:
data_ohe = data.drop(['Model', 'Brand'], axis=1)
data_ohe = pd.get_dummies(data_ohe)
print(data_ohe.shape)
data_ohe.head()

(314100, 28)

,Price,RegistrationYear,Power,Kilometer,RegistrationMonth,VehicleType_bus,VehicleType_convertible,VehicleType_coupe,VehicleType_other,VehicleType_sedan,...,FuelType_electric,FuelType_gasoline,FuelType_hybrid,FuelType_lpg,FuelType_other,FuelType_petrol,FuelType_unknown,NotRepaired_no,NotRepaired_unknown,NotRepaired_yes
1,18300,2011,190,125000,5,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,1
2,9800,2004,163,125000,8,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
3,1500,2001,75,150000,6,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
4,3600,2008,69,90000,7,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
5,650,1995,102,150000,10,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,1

Ordinal encoding

In [13]:
from sklearn.preprocessing import OrdinalEncoder

data[categorical_features] = OrdinalEncoder().fit_transform(data[categorical_features])

data.head()

,Price,VehicleType,RegistrationYear,Gearbox,Power,Model,Kilometer,RegistrationMonth,FuelType,Brand,NotRepaired
1,18300,2.0,2011,1.0,190,227.0,125000,5,2.0,1.0,2.0
2,9800,6.0,2004,0.0,163,117.0,125000,8,2.0,14.0,1.0
3,1500,5.0,2001,1.0,75,116.0,150000,6,6.0,38.0,0.0
4,3600,5.0,2008,1.0,69,101.0,90000,7,2.0,31.0,0.0
5,650,4.0,1995,1.0,102,11.0,150000,10,6.0,2.0,2.0

### Split into train-validation-test

In [14]:
from sklearn.model_selection import train_test_split

index_train_valid, index_test = train_test_split(data.index, test_size=0.2, random_state=12345)
index_train, index_valid = train_test_split(index_train_valid, test_size=0.25, random_state=54321)

data_train = data.loc[index_train]
data_valid = data.loc[index_valid]
data_test = data.loc[index_test]

data_ohe_train = data_ohe.loc[index_train]
data_ohe_valid = data_ohe.loc[index_valid]
data_ohe_test = data_ohe.loc[index_test]

print(data_train.shape)
print(data_valid.shape)
print(data_test.shape)

print(data_ohe_train.shape)
print(data_ohe_valid.shape)
print(data_ohe_test.shape)

(188460, 11)
(62820, 11)
(62820, 11)
(188460, 28)
(62820, 28)
(62820, 28)

# 2. Model training

In [15]:
from sklearn.metrics import mean_squared_error

def rmse(y, a):
    return mean_squared_error(y, a)**0.5

Constant model

In [16]:
pred_mean = np.ones(data['Price'].shape) * data['Price'].mean()
print(rmse(data['Price'], pred_mean))

4590.240919951061

### Models with OHE

In [17]:
features_train = data_ohe_train.drop(['Price'], axis=1)
target_train = data_ohe_train['Price']
features_valid = data_ohe_valid.drop(['Price'], axis=1)
target_valid = data_ohe_valid['Price']
features_test = data_ohe_test.drop(['Price'], axis=1)
target_test = data_ohe_test['Price']

**Linear regression**

In [18]:
%%time

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(features_train, target_train)

CPU times: user 358 ms, sys: 66.9 ms, total: 425 ms
Wall time: 398 ms

In [19]:
%%time

pred_train = model.predict(features_train)
pred_valid = model.predict(features_valid)
pred_test = model.predict(features_test)

CPU times: user 57.9 ms, sys: 32 ms, total: 89.9 ms
Wall time: 111 ms

In [20]:
print("Train RMSE:", rmse(target_train, pred_train).round(5))
print("Valid RMSE:", rmse(target_valid, pred_valid).round(5))
print("Test RMSE: ", rmse(target_test, pred_test).round(5))

Train RMSE: 3238.30929
Valid RMSE: 3216.58303
Test RMSE:  3223.39036

### Models with ordinal encoding

In [21]:
features_train = data_train.drop(['Price'], axis=1)
target_train = data_train['Price']
features_valid = data_valid.drop(['Price'], axis=1)
target_valid = data_valid['Price']
features_test = data_test.drop(['Price'], axis=1)
target_test = data_test['Price']

**Random forrest**

In [22]:
from sklearn.ensemble import RandomForestRegressor

for depth in [1, 2, 4, 6, 8, None]:
    model = RandomForestRegressor(max_depth=depth, n_estimators=100)
    model.fit(features_train, target_train)
    
    pred_train = model.predict(features_train)
    pred_valid = model.predict(features_valid)
    print("Depth:", depth)
    print("Train RMSE:", rmse(target_train, pred_train).round(5))
    print("Valid RMSE:", rmse(target_valid, pred_valid).round(5))

Depth: 1
Train RMSE: 3790.22028
Valid RMSE: 3782.28954
Depth: 2
Train RMSE: 3329.79646
Valid RMSE: 3318.93867
Depth: 4
Train RMSE: 2691.49521
Valid RMSE: 2677.68587
Depth: 6
Train RMSE: 2332.27542
Valid RMSE: 2333.8505
Depth: 8
Train RMSE: 2099.20864
Valid RMSE: 2124.48877
Depth: None
Train RMSE: 771.00994
Valid RMSE: 1729.71112

In [23]:
%%time

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100, max_depth=None)
model.fit(features_train, target_train)

CPU times: user 1min 16s, sys: 1.86 s, total: 1min 18s
Wall time: 1min 27s

In [24]:
%%time

pred_train = model.predict(features_train)
pred_valid = model.predict(features_valid)
pred_test = model.predict(features_test)

CPU times: user 17 s, sys: 257 ms, total: 17.3 s
Wall time: 19.4 s

In [25]:
print("Train RMSE:", rmse(target_train, pred_train).round(5))
print("Valid RMSE:", rmse(target_valid, pred_valid).round(5))
print("Test RMSE: ", rmse(target_test, pred_test).round(5))

Train RMSE: 771.64466
Valid RMSE: 1732.70045
Test RMSE:  1728.78498

**Gradient boosting LightGBM**

In [26]:
%%time

import lightgbm as lgb

model = lgb.LGBMRegressor(num_iterations=1000, vebose=1, metric='rmse')
model.fit(features_train, target_train, 
          eval_set=(features_valid, target_valid),
          categorical_feature=categorical_features)

/usr/local/lib/python3.7/site-packages/lightgbm/__init__.py:46: UserWarning: Starting from version 2.2.1, the library file in distribution wheels for macOS is built by the Apple Clang (Xcode_8.3.3) compiler.
This means that in case of installing LightGBM from PyPI via the ``pip install lightgbm`` command, you don't need to install the gcc compiler anymore.
Instead of that, you need to install the OpenMP library, which is required for running LightGBM on the system with the Apple Clang compiler.
You can install the OpenMP library by the following command: ``brew install libomp``.
  "You can install the OpenMP library by the following command: ``brew install libomp``.", UserWarning)
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:118: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
/usr/local/lib/python3.7/site-packages/lightgbm/basic.py:1209: UserWarning: categorical_feature in Dataset is overridden.
New categorical_feature is ['Brand', 'FuelType', 'Gearbox', 'Model', 'NotRepaired', 'VehicleType']
  'New categorical_feature is {}'.format(sorted(list(categorical_feature))))

[1]	valid_0's rmse: 4264.85
[2]	valid_0's rmse: 3979.75
[3]	valid_0's rmse: 3730.63
[4]	valid_0's rmse: 3509.73
[5]	valid_0's rmse: 3314.84
[6]	valid_0's rmse: 3143.37
[7]	valid_0's rmse: 2990.09
[8]	valid_0's rmse: 2852.56
[9]	valid_0's rmse: 2734.12
[10]	valid_0's rmse: 2626.74
[11]	valid_0's rmse: 2535
[12]	valid_0's rmse: 2451.28
[13]	valid_0's rmse: 2380.15
[14]	valid_0's rmse: 2316.23
[15]	valid_0's rmse: 2258.4
[16]	valid_0's rmse: 2209.11
[17]	valid_0's rmse: 2163.7
[18]	valid_0's rmse: 2125.11
[19]	valid_0's rmse: 2090.67
[20]	valid_0's rmse: 2060.78
[21]	valid_0's rmse: 2033.48
[22]	valid_0's rmse: 2010.38
[23]	valid_0's rmse: 1989.39
[24]	valid_0's rmse: 1970.55
[25]	valid_0's rmse: 1954.17
[26]	valid_0's rmse: 1938.74
[27]	valid_0's rmse: 1925.01
[28]	valid_0's rmse: 1912.61
[29]	valid_0's rmse: 1901.93
[30]	valid_0's rmse: 1890.83
[31]	valid_0's rmse: 1882.13
[32]	valid_0's rmse: 1874.62
[33]	valid_0's rmse: 1866.91
[34]	valid_0's rmse: 1859.39
[35]	valid_0's rmse: 1853.48
[36]	valid_0's rmse: 1846.88
[37]	valid_0's rmse: 1842.42
[38]	valid_0's rmse: 1837.72
[39]	valid_0's rmse: 1833.34
[40]	valid_0's rmse: 1828.61
[41]	valid_0's rmse: 1824.66
[42]	valid_0's rmse: 1820.77
[43]	valid_0's rmse: 1817.3
[44]	valid_0's rmse: 1814.2
[45]	valid_0's rmse: 1810.9
[46]	valid_0's rmse: 1808.7
[47]	valid_0's rmse: 1806.21
[48]	valid_0's rmse: 1804.4
[49]	valid_0's rmse: 1802.44
[50]	valid_0's rmse: 1799.76
[51]	valid_0's rmse: 1797.5
[52]	valid_0's rmse: 1795.45
[53]	valid_0's rmse: 1793.18
[54]	valid_0's rmse: 1791.39
[55]	valid_0's rmse: 1789.32
[56]	valid_0's rmse: 1787.29
[57]	valid_0's rmse: 1785.94
[58]	valid_0's rmse: 1783.99
[59]	valid_0's rmse: 1782.42
[60]	valid_0's rmse: 1781.3
[61]	valid_0's rmse: 1779.99
[62]	valid_0's rmse: 1778.37
[63]	valid_0's rmse: 1776.97
[64]	valid_0's rmse: 1775.66
[65]	valid_0's rmse: 1774.73
[66]	valid_0's rmse: 1773.43
[67]	valid_0's rmse: 1771.81
[68]	valid_0's rmse: 1770.73
[69]	valid_0's rmse: 1769.16
[70]	valid_0's rmse: 1767.92
[71]	valid_0's rmse: 1766.59
[72]	valid_0's rmse: 1765.76
[73]	valid_0's rmse: 1764.74
[74]	valid_0's rmse: 1763.68
[75]	valid_0's rmse: 1762.78
[76]	valid_0's rmse: 1762.13
[77]	valid_0's rmse: 1760.83
[78]	valid_0's rmse: 1760.32
[79]	valid_0's rmse: 1759.45
[80]	valid_0's rmse: 1758.34
[81]	valid_0's rmse: 1757.77
[82]	valid_0's rmse: 1756.53
[83]	valid_0's rmse: 1756.3
[84]	valid_0's rmse: 1755.63
[85]	valid_0's rmse: 1754.82
[86]	valid_0's rmse: 1754.01
[87]	valid_0's rmse: 1753.22
[88]	valid_0's rmse: 1752.64
[89]	valid_0's rmse: 1752
[90]	valid_0's rmse: 1751.35
[91]	valid_0's rmse: 1750.98
[92]	valid_0's rmse: 1750.35
[93]	valid_0's rmse: 1748.74
[94]	valid_0's rmse: 1748.13
[95]	valid_0's rmse: 1747.95
[96]	valid_0's rmse: 1747.14
[97]	valid_0's rmse: 1746.68
[98]	valid_0's rmse: 1746.19
[99]	valid_0's rmse: 1745.75
[100]	valid_0's rmse: 1745.5
[101]	valid_0's rmse: 1745.15
[102]	valid_0's rmse: 1744.37
[103]	valid_0's rmse: 1744.3
[104]	valid_0's rmse: 1743.74
[105]	valid_0's rmse: 1742.96
[106]	valid_0's rmse: 1742.48
[107]	valid_0's rmse: 1741.99
[108]	valid_0's rmse: 1741.53
[109]	valid_0's rmse: 1741.16
[110]	valid_0's rmse: 1740.72
[111]	valid_0's rmse: 1740.63
[112]	valid_0's rmse: 1739.85
[113]	valid_0's rmse: 1738.92
[114]	valid_0's rmse: 1738.54
[115]	valid_0's rmse: 1737.85
[116]	valid_0's rmse: 1737.55
[117]	valid_0's rmse: 1737.45
[118]	valid_0's rmse: 1736.83
[119]	valid_0's rmse: 1736.18
[120]	valid_0's rmse: 1735.48
[121]	valid_0's rmse: 1735.09
[122]	valid_0's rmse: 1734.52
[123]	valid_0's rmse: 1734.17
[124]	valid_0's rmse: 1733.66
[125]	valid_0's rmse: 1732.7
[126]	valid_0's rmse: 1732.5
[127]	valid_0's rmse: 1731.63
[128]	valid_0's rmse: 1731.62
[129]	valid_0's rmse: 1731.19
[130]	valid_0's rmse: 1730.53
[131]	valid_0's rmse: 1730.23
[132]	valid_0's rmse: 1729.89
[133]	valid_0's rmse: 1729.66
[134]	valid_0's rmse: 1729.17
[135]	valid_0's rmse: 1728.85
[136]	valid_0's rmse: 1728.67
[137]	valid_0's rmse: 1728.37
[138]	valid_0's rmse: 1727.61
[139]	valid_0's rmse: 1726.48
[140]	valid_0's rmse: 1725.82
[141]	valid_0's rmse: 1725.36
[142]	valid_0's rmse: 1725.22
[143]	valid_0's rmse: 1725
[144]	valid_0's rmse: 1724.27
[145]	valid_0's rmse: 1723.99
[146]	valid_0's rmse: 1723.74
[147]	valid_0's rmse: 1723.58
[148]	valid_0's rmse: 1723.45
[149]	valid_0's rmse: 1722.88
[150]	valid_0's rmse: 1722.66
[151]	valid_0's rmse: 1722.5
[152]	valid_0's rmse: 1722.51
[153]	valid_0's rmse: 1722.25
[154]	valid_0's rmse: 1721.63
[155]	valid_0's rmse: 1720.89
[156]	valid_0's rmse: 1720.61
[157]	valid_0's rmse: 1720.31
[158]	valid_0's rmse: 1719.93
[159]	valid_0's rmse: 1719.87
[160]	valid_0's rmse: 1719.32
[161]	valid_0's rmse: 1718.45
[162]	valid_0's rmse: 1718.13
[163]	valid_0's rmse: 1718.04
[164]	valid_0's rmse: 1717.82
[165]	valid_0's rmse: 1717.57
[166]	valid_0's rmse: 1717.43
[167]	valid_0's rmse: 1716.91
[168]	valid_0's rmse: 1716.74
[169]	valid_0's rmse: 1716.47
[170]	valid_0's rmse: 1716.35
[171]	valid_0's rmse: 1716.13
[172]	valid_0's rmse: 1715.65
[173]	valid_0's rmse: 1715.3
[174]	valid_0's rmse: 1714.83
[175]	valid_0's rmse: 1714.64
[176]	valid_0's rmse: 1714.33
[177]	valid_0's rmse: 1713.82
[178]	valid_0's rmse: 1713.48
[179]	valid_0's rmse: 1713.24
[180]	valid_0's rmse: 1713.19
[181]	valid_0's rmse: 1713.02
[182]	valid_0's rmse: 1712.64
[183]	valid_0's rmse: 1712.51
[184]	valid_0's rmse: 1712.23
[185]	valid_0's rmse: 1711.91
[186]	valid_0's rmse: 1711.54
[187]	valid_0's rmse: 1711.24
[188]	valid_0's rmse: 1710.9
[189]	valid_0's rmse: 1710.73
[190]	valid_0's rmse: 1710.41
[191]	valid_0's rmse: 1709.56
[192]	valid_0's rmse: 1709.53
[193]	valid_0's rmse: 1709.49
[194]	valid_0's rmse: 1709.33
[195]	valid_0's rmse: 1709.24
[196]	valid_0's rmse: 1708.92
[197]	valid_0's rmse: 1708.55
[198]	valid_0's rmse: 1708.09
[199]	valid_0's rmse: 1707.97
[200]	valid_0's rmse: 1707.83
[201]	valid_0's rmse: 1707.36
[202]	valid_0's rmse: 1707.22
[203]	valid_0's rmse: 1706.97
[204]	valid_0's rmse: 1706.84
[205]	valid_0's rmse: 1706.67
[206]	valid_0's rmse: 1706.27
[207]	valid_0's rmse: 1705.57
[208]	valid_0's rmse: 1705.45
[209]	valid_0's rmse: 1705.24
[210]	valid_0's rmse: 1705.15
[211]	valid_0's rmse: 1705.18
[212]	valid_0's rmse: 1705.05
[213]	valid_0's rmse: 1705
[214]	valid_0's rmse: 1704.8
[215]	valid_0's rmse: 1704.79
[216]	valid_0's rmse: 1704.63
[217]	valid_0's rmse: 1704.26
[218]	valid_0's rmse: 1703.61
[219]	valid_0's rmse: 1703.41
[220]	valid_0's rmse: 1703.3
[221]	valid_0's rmse: 1703.21
[222]	valid_0's rmse: 1702.87
[223]	valid_0's rmse: 1702.77
[224]	valid_0's rmse: 1702.64
[225]	valid_0's rmse: 1702.6
[226]	valid_0's rmse: 1702.58
[227]	valid_0's rmse: 1702.06
[228]	valid_0's rmse: 1701.92
[229]	valid_0's rmse: 1701.75
[230]	valid_0's rmse: 1701.49
[231]	valid_0's rmse: 1701.39
[232]	valid_0's rmse: 1701.35
[233]	valid_0's rmse: 1701.17
[234]	valid_0's rmse: 1701.03
[235]	valid_0's rmse: 1700.79
[236]	valid_0's rmse: 1700.43
[237]	valid_0's rmse: 1700.11
[238]	valid_0's rmse: 1699.91
[239]	valid_0's rmse: 1699.26
[240]	valid_0's rmse: 1699.09
[241]	valid_0's rmse: 1698.81
[242]	valid_0's rmse: 1698.66
[243]	valid_0's rmse: 1698.63
[244]	valid_0's rmse: 1698.62
[245]	valid_0's rmse: 1698.19
[246]	valid_0's rmse: 1698.1
[247]	valid_0's rmse: 1697.86
[248]	valid_0's rmse: 1697.81
[249]	valid_0's rmse: 1697.66
[250]	valid_0's rmse: 1697.43
[251]	valid_0's rmse: 1697.38
[252]	valid_0's rmse: 1697.27
[253]	valid_0's rmse: 1697.24
[254]	valid_0's rmse: 1697.17
[255]	valid_0's rmse: 1696.91
[256]	valid_0's rmse: 1696.75
[257]	valid_0's rmse: 1696.51
[258]	valid_0's rmse: 1696.25
[259]	valid_0's rmse: 1696.31
[260]	valid_0's rmse: 1695.88
[261]	valid_0's rmse: 1695.52
[262]	valid_0's rmse: 1695.39
[263]	valid_0's rmse: 1695.16
[264]	valid_0's rmse: 1694.88
[265]	valid_0's rmse: 1694.82
[266]	valid_0's rmse: 1694.71
[267]	valid_0's rmse: 1694.63
[268]	valid_0's rmse: 1694.6
[269]	valid_0's rmse: 1694.57
[270]	valid_0's rmse: 1694.49
[271]	valid_0's rmse: 1694.43
[272]	valid_0's rmse: 1694.34
[273]	valid_0's rmse: 1693.87
[274]	valid_0's rmse: 1693.47
[275]	valid_0's rmse: 1693.25
[276]	valid_0's rmse: 1693.11
[277]	valid_0's rmse: 1693.02
[278]	valid_0's rmse: 1692.76
[279]	valid_0's rmse: 1692.93
[280]	valid_0's rmse: 1692.79
[281]	valid_0's rmse: 1692.45
[282]	valid_0's rmse: 1692.34
[283]	valid_0's rmse: 1691.94
[284]	valid_0's rmse: 1691.83
[285]	valid_0's rmse: 1691.65
[286]	valid_0's rmse: 1691.6
[287]	valid_0's rmse: 1691.52
[288]	valid_0's rmse: 1691.39
[289]	valid_0's rmse: 1691.27
[290]	valid_0's rmse: 1691.15

[291]	valid_0's rmse: 1690.74
[292]	valid_0's rmse: 1690.63
[293]	valid_0's rmse: 1690.69
[294]	valid_0's rmse: 1690.63
[295]	valid_0's rmse: 1690.61
[296]	valid_0's rmse: 1690.57
[297]	valid_0's rmse: 1690.4
[298]	valid_0's rmse: 1689.92
[299]	valid_0's rmse: 1689.88
[300]	valid_0's rmse: 1689.85
[301]	valid_0's rmse: 1689.72
[302]	valid_0's rmse: 1689.68
[303]	valid_0's rmse: 1689.19
[304]	valid_0's rmse: 1689.04
[305]	valid_0's rmse: 1688.95
[306]	valid_0's rmse: 1688.82
[307]	valid_0's rmse: 1688.61
[308]	valid_0's rmse: 1688.51
[309]	valid_0's rmse: 1688.43
[310]	valid_0's rmse: 1688.33
[311]	valid_0's rmse: 1688.35
[312]	valid_0's rmse: 1688.23
[313]	valid_0's rmse: 1688.23
[314]	valid_0's rmse: 1688.2
[315]	valid_0's rmse: 1688.09
[316]	valid_0's rmse: 1687.97
[317]	valid_0's rmse: 1688.05
[318]	valid_0's rmse: 1688.09
[319]	valid_0's rmse: 1687.99
[320]	valid_0's rmse: 1687.67
[321]	valid_0's rmse: 1687.31
[322]	valid_0's rmse: 1687.15
[323]	valid_0's rmse: 1686.81
[324]	valid_0's rmse: 1686.68
[325]	valid_0's rmse: 1686.38
[326]	valid_0's rmse: 1686.26
[327]	valid_0's rmse: 1686.19
[328]	valid_0's rmse: 1686.13
[329]	valid_0's rmse: 1685.9
[330]	valid_0's rmse: 1685.85
[331]	valid_0's rmse: 1685.7
[332]	valid_0's rmse: 1685.71
[333]	valid_0's rmse: 1685.63
[334]	valid_0's rmse: 1685.51
[335]	valid_0's rmse: 1685.34
[336]	valid_0's rmse: 1685.19
[337]	valid_0's rmse: 1684.83
[338]	valid_0's rmse: 1684.74
[339]	valid_0's rmse: 1684.53
[340]	valid_0's rmse: 1684.42
[341]	valid_0's rmse: 1684.41
[342]	valid_0's rmse: 1684.23
[343]	valid_0's rmse: 1683.82
[344]	valid_0's rmse: 1683.75
[345]	valid_0's rmse: 1683.61
[346]	valid_0's rmse: 1683.63
[347]	valid_0's rmse: 1683.52
[348]	valid_0's rmse: 1683.44
[349]	valid_0's rmse: 1683.24
[350]	valid_0's rmse: 1683.25
[351]	valid_0's rmse: 1683.18
[352]	valid_0's rmse: 1683.07
[353]	valid_0's rmse: 1682.83
[354]	valid_0's rmse: 1682.82
[355]	valid_0's rmse: 1682.76
[356]	valid_0's rmse: 1682.71
[357]	valid_0's rmse: 1682.63
[358]	valid_0's rmse: 1682.55
[359]	valid_0's rmse: 1682.47
[360]	valid_0's rmse: 1681.99
[361]	valid_0's rmse: 1681.97
[362]	valid_0's rmse: 1681.9
[363]	valid_0's rmse: 1681.83
[364]	valid_0's rmse: 1681.5
[365]	valid_0's rmse: 1681.19
[366]	valid_0's rmse: 1681.22
[367]	valid_0's rmse: 1680.95
[368]	valid_0's rmse: 1680.8
[369]	valid_0's rmse: 1680.92
[370]	valid_0's rmse: 1680.82
[371]	valid_0's rmse: 1680.78
[372]	valid_0's rmse: 1680.72
[373]	valid_0's rmse: 1680.44
[374]	valid_0's rmse: 1680.17
[375]	valid_0's rmse: 1679.99
[376]	valid_0's rmse: 1679.73
[377]	valid_0's rmse: 1679.61
[378]	valid_0's rmse: 1679.45
[379]	valid_0's rmse: 1679.27
[380]	valid_0's rmse: 1679.04
[381]	valid_0's rmse: 1679.08
[382]	valid_0's rmse: 1678.83
[383]	valid_0's rmse: 1678.8
[384]	valid_0's rmse: 1678.77
[385]	valid_0's rmse: 1678.64
[386]	valid_0's rmse: 1678.53
[387]	valid_0's rmse: 1678.47
[388]	valid_0's rmse: 1678.34
[389]	valid_0's rmse: 1678.23
[390]	valid_0's rmse: 1678.06
[391]	valid_0's rmse: 1678.04
[392]	valid_0's rmse: 1677.84
[393]	valid_0's rmse: 1677.77
[394]	valid_0's rmse: 1677.62
[395]	valid_0's rmse: 1677.62
[396]	valid_0's rmse: 1677.52
[397]	valid_0's rmse: 1677.43
[398]	valid_0's rmse: 1677.39
[399]	valid_0's rmse: 1677.23
[400]	valid_0's rmse: 1677.14
[401]	valid_0's rmse: 1677.06
[402]	valid_0's rmse: 1677.03
[403]	valid_0's rmse: 1676.98
[404]	valid_0's rmse: 1676.96
[405]	valid_0's rmse: 1676.67
[406]	valid_0's rmse: 1676.43
[407]	valid_0's rmse: 1676.25
[408]	valid_0's rmse: 1675.95
[409]	valid_0's rmse: 1675.85
[410]	valid_0's rmse: 1675.68
[411]	valid_0's rmse: 1675.65
[412]	valid_0's rmse: 1675.51
[413]	valid_0's rmse: 1675.27
[414]	valid_0's rmse: 1675.08
[415]	valid_0's rmse: 1674.91
[416]	valid_0's rmse: 1674.9
[417]	valid_0's rmse: 1674.77
[418]	valid_0's rmse: 1674.72
[419]	valid_0's rmse: 1674.66
[420]	valid_0's rmse: 1674.67
[421]	valid_0's rmse: 1674.64
[422]	valid_0's rmse: 1674.54
[423]	valid_0's rmse: 1674.54
[424]	valid_0's rmse: 1674.3
[425]	valid_0's rmse: 1674.27
[426]	valid_0's rmse: 1674.22
[427]	valid_0's rmse: 1674.15
[428]	valid_0's rmse: 1674.06
[429]	valid_0's rmse: 1673.83
[430]	valid_0's rmse: 1673.73
[431]	valid_0's rmse: 1673.61
[432]	valid_0's rmse: 1673.6
[433]	valid_0's rmse: 1673.47
[434]	valid_0's rmse: 1673.35
[435]	valid_0's rmse: 1673.26
[436]	valid_0's rmse: 1673.22
[437]	valid_0's rmse: 1673.16
[438]	valid_0's rmse: 1673.09
[439]	valid_0's rmse: 1673.04
[440]	valid_0's rmse: 1672.79
[441]	valid_0's rmse: 1672.43
[442]	valid_0's rmse: 1672.44
[443]	valid_0's rmse: 1672.41
[444]	valid_0's rmse: 1672.4
[445]	valid_0's rmse: 1672.33
[446]	valid_0's rmse: 1672.33
[447]	valid_0's rmse: 1672.28
[448]	valid_0's rmse: 1672.29
[449]	valid_0's rmse: 1672.25
[450]	valid_0's rmse: 1672.24
[451]	valid_0's rmse: 1672.27
[452]	valid_0's rmse: 1672.19
[453]	valid_0's rmse: 1672.16
[454]	valid_0's rmse: 1672.19
[455]	valid_0's rmse: 1672.19
[456]	valid_0's rmse: 1672.16
[457]	valid_0's rmse: 1672.06
[458]	valid_0's rmse: 1672.07
[459]	valid_0's rmse: 1671.9
[460]	valid_0's rmse: 1671.92
[461]	valid_0's rmse: 1671.81
[462]	valid_0's rmse: 1671.62
[463]	valid_0's rmse: 1671.55
[464]	valid_0's rmse: 1671.54
[465]	valid_0's rmse: 1671.53
[466]	valid_0's rmse: 1671.47
[467]	valid_0's rmse: 1671.44
[468]	valid_0's rmse: 1671.46
[469]	valid_0's rmse: 1671.53
[470]	valid_0's rmse: 1671.52
[471]	valid_0's rmse: 1671.49
[472]	valid_0's rmse: 1671.36
[473]	valid_0's rmse: 1671.34
[474]	valid_0's rmse: 1671.23
[475]	valid_0's rmse: 1671.24
[476]	valid_0's rmse: 1671.11
[477]	valid_0's rmse: 1671.14
[478]	valid_0's rmse: 1671.07
[479]	valid_0's rmse: 1671.05
[480]	valid_0's rmse: 1671
[481]	valid_0's rmse: 1670.99
[482]	valid_0's rmse: 1671.01
[483]	valid_0's rmse: 1671.06
[484]	valid_0's rmse: 1670.97
[485]	valid_0's rmse: 1670.83
[486]	valid_0's rmse: 1670.73
[487]	valid_0's rmse: 1670.53
[488]	valid_0's rmse: 1670.43
[489]	valid_0's rmse: 1670.38
[490]	valid_0's rmse: 1670.32
[491]	valid_0's rmse: 1670.22
[492]	valid_0's rmse: 1670.1
[493]	valid_0's rmse: 1670.17
[494]	valid_0's rmse: 1670.06
[495]	valid_0's rmse: 1669.84
[496]	valid_0's rmse: 1669.76
[497]	valid_0's rmse: 1669.79
[498]	valid_0's rmse: 1669.65
[499]	valid_0's rmse: 1669.5
[500]	valid_0's rmse: 1669.35
[501]	valid_0's rmse: 1669.24
[502]	valid_0's rmse: 1669.19
[503]	valid_0's rmse: 1669.22
[504]	valid_0's rmse: 1669.18
[505]	valid_0's rmse: 1669.22
[506]	valid_0's rmse: 1669.22
[507]	valid_0's rmse: 1669.21
[508]	valid_0's rmse: 1669.07
[509]	valid_0's rmse: 1668.98
[510]	valid_0's rmse: 1669
[511]	valid_0's rmse: 1668.9
[512]	valid_0's rmse: 1668.79
[513]	valid_0's rmse: 1668.7
[514]	valid_0's rmse: 1668.56
[515]	valid_0's rmse: 1668.62
[516]	valid_0's rmse: 1668.59
[517]	valid_0's rmse: 1668.51
[518]	valid_0's rmse: 1668.42
[519]	valid_0's rmse: 1668.47
[520]	valid_0's rmse: 1668.13
[521]	valid_0's rmse: 1668.11
[522]	valid_0's rmse: 1668.11
[523]	valid_0's rmse: 1668
[524]	valid_0's rmse: 1667.99
[525]	valid_0's rmse: 1667.99
[526]	valid_0's rmse: 1667.89
[527]	valid_0's rmse: 1667.86
[528]	valid_0's rmse: 1667.75
[529]	valid_0's rmse: 1667.83
[530]	valid_0's rmse: 1667.87
[531]	valid_0's rmse: 1667.88
[532]	valid_0's rmse: 1667.84
[533]	valid_0's rmse: 1667.83
[534]	valid_0's rmse: 1667.75
[535]	valid_0's rmse: 1667.75
[536]	valid_0's rmse: 1667.82
[537]	valid_0's rmse: 1667.78
[538]	valid_0's rmse: 1667.76
[539]	valid_0's rmse: 1667.62
[540]	valid_0's rmse: 1667.54
[541]	valid_0's rmse: 1667.5
[542]	valid_0's rmse: 1667.6
[543]	valid_0's rmse: 1667.52
[544]	valid_0's rmse: 1667.47
[545]	valid_0's rmse: 1667.44
[546]	valid_0's rmse: 1667.33
[547]	valid_0's rmse: 1667.27
[548]	valid_0's rmse: 1667.28
[549]	valid_0's rmse: 1667.21
[550]	valid_0's rmse: 1667.18
[551]	valid_0's rmse: 1667.04
[552]	valid_0's rmse: 1667
[553]	valid_0's rmse: 1666.99
[554]	valid_0's rmse: 1666.96
[555]	valid_0's rmse: 1666.98
[556]	valid_0's rmse: 1666.77
[557]	valid_0's rmse: 1666.81
[558]	valid_0's rmse: 1666.74
[559]	valid_0's rmse: 1666.56
[560]	valid_0's rmse: 1666.43
[561]	valid_0's rmse: 1666.48
[562]	valid_0's rmse: 1666.46
[563]	valid_0's rmse: 1666.41
[564]	valid_0's rmse: 1666.42
[565]	valid_0's rmse: 1666.4
[566]	valid_0's rmse: 1666.4
[567]	valid_0's rmse: 1666.35
[568]	valid_0's rmse: 1666.29
[569]	valid_0's rmse: 1666.26
[570]	valid_0's rmse: 1666.12

[571]	valid_0's rmse: 1665.98
[572]	valid_0's rmse: 1665.95
[573]	valid_0's rmse: 1665.99
[574]	valid_0's rmse: 1666.05
[575]	valid_0's rmse: 1666.02
[576]	valid_0's rmse: 1665.96
[577]	valid_0's rmse: 1665.76
[578]	valid_0's rmse: 1665.57
[579]	valid_0's rmse: 1665.51
[580]	valid_0's rmse: 1665.45
[581]	valid_0's rmse: 1665.39
[582]	valid_0's rmse: 1665.44
[583]	valid_0's rmse: 1665.49
[584]	valid_0's rmse: 1665.42
[585]	valid_0's rmse: 1665.49
[586]	valid_0's rmse: 1665.49
[587]	valid_0's rmse: 1665.43
[588]	valid_0's rmse: 1665.47
[589]	valid_0's rmse: 1665.45
[590]	valid_0's rmse: 1665.41
[591]	valid_0's rmse: 1665.36
[592]	valid_0's rmse: 1665.41
[593]	valid_0's rmse: 1665.37
[594]	valid_0's rmse: 1665.36
[595]	valid_0's rmse: 1665.28
[596]	valid_0's rmse: 1665.26
[597]	valid_0's rmse: 1665.28
[598]	valid_0's rmse: 1665.28
[599]	valid_0's rmse: 1665.31
[600]	valid_0's rmse: 1665.31
[601]	valid_0's rmse: 1665.34
[602]	valid_0's rmse: 1665.31
[603]	valid_0's rmse: 1665.31
[604]	valid_0's rmse: 1665.29
[605]	valid_0's rmse: 1665.28
[606]	valid_0's rmse: 1665.16
[607]	valid_0's rmse: 1665.18
[608]	valid_0's rmse: 1665.23
[609]	valid_0's rmse: 1665.27
[610]	valid_0's rmse: 1665.25
[611]	valid_0's rmse: 1665.19
[612]	valid_0's rmse: 1664.95
[613]	valid_0's rmse: 1664.9
[614]	valid_0's rmse: 1664.86
[615]	valid_0's rmse: 1664.81
[616]	valid_0's rmse: 1664.81
[617]	valid_0's rmse: 1664.79
[618]	valid_0's rmse: 1664.83
[619]	valid_0's rmse: 1664.77
[620]	valid_0's rmse: 1664.68
[621]	valid_0's rmse: 1664.61
[622]	valid_0's rmse: 1664.38
[623]	valid_0's rmse: 1664.25
[624]	valid_0's rmse: 1663.92
[625]	valid_0's rmse: 1663.78
[626]	valid_0's rmse: 1663.84
[627]	valid_0's rmse: 1663.77
[628]	valid_0's rmse: 1663.75
[629]	valid_0's rmse: 1663.7
[630]	valid_0's rmse: 1663.65
[631]	valid_0's rmse: 1663.55
[632]	valid_0's rmse: 1663.45
[633]	valid_0's rmse: 1663.41
[634]	valid_0's rmse: 1663.13
[635]	valid_0's rmse: 1663
[636]	valid_0's rmse: 1662.92
[637]	valid_0's rmse: 1662.83
[638]	valid_0's rmse: 1662.85
[639]	valid_0's rmse: 1662.87
[640]	valid_0's rmse: 1662.86
[641]	valid_0's rmse: 1662.6
[642]	valid_0's rmse: 1662.41
[643]	valid_0's rmse: 1662.29
[644]	valid_0's rmse: 1662.21
[645]	valid_0's rmse: 1662.19
[646]	valid_0's rmse: 1662.09
[647]	valid_0's rmse: 1662.08
[648]	valid_0's rmse: 1662.12
[649]	valid_0's rmse: 1662.1
[650]	valid_0's rmse: 1662.15
[651]	valid_0's rmse: 1662.08
[652]	valid_0's rmse: 1662.06
[653]	valid_0's rmse: 1662
[654]	valid_0's rmse: 1661.97
[655]	valid_0's rmse: 1661.98
[656]	valid_0's rmse: 1661.85
[657]	valid_0's rmse: 1661.91
[658]	valid_0's rmse: 1661.84
[659]	valid_0's rmse: 1661.77
[660]	valid_0's rmse: 1661.79
[661]	valid_0's rmse: 1661.79
[662]	valid_0's rmse: 1661.62
[663]	valid_0's rmse: 1661.47
[664]	valid_0's rmse: 1661.44
[665]	valid_0's rmse: 1661.44
[666]	valid_0's rmse: 1661.4
[667]	valid_0's rmse: 1661.42
[668]	valid_0's rmse: 1661.29
[669]	valid_0's rmse: 1661.29
[670]	valid_0's rmse: 1661.28
[671]	valid_0's rmse: 1661.29
[672]	valid_0's rmse: 1661.37
[673]	valid_0's rmse: 1661.28
[674]	valid_0's rmse: 1661.27
[675]	valid_0's rmse: 1661.32
[676]	valid_0's rmse: 1661.13
[677]	valid_0's rmse: 1661.09
[678]	valid_0's rmse: 1661.08
[679]	valid_0's rmse: 1660.96
[680]	valid_0's rmse: 1660.91
[681]	valid_0's rmse: 1660.92
[682]	valid_0's rmse: 1660.68
[683]	valid_0's rmse: 1660.65
[684]	valid_0's rmse: 1660.4
[685]	valid_0's rmse: 1660.4
[686]	valid_0's rmse: 1660.48
[687]	valid_0's rmse: 1660.41
[688]	valid_0's rmse: 1660.42
[689]	valid_0's rmse: 1660.41
[690]	valid_0's rmse: 1660.44
[691]	valid_0's rmse: 1660.49
[692]	valid_0's rmse: 1660.49
[693]	valid_0's rmse: 1660.44
[694]	valid_0's rmse: 1660.31
[695]	valid_0's rmse: 1660.29
[696]	valid_0's rmse: 1660.28
[697]	valid_0's rmse: 1660.22
[698]	valid_0's rmse: 1660.08
[699]	valid_0's rmse: 1660.08
[700]	valid_0's rmse: 1660.08
[701]	valid_0's rmse: 1660.06
[702]	valid_0's rmse: 1660.19
[703]	valid_0's rmse: 1660.21
[704]	valid_0's rmse: 1660.04
[705]	valid_0's rmse: 1659.97
[706]	valid_0's rmse: 1659.93
[707]	valid_0's rmse: 1659.88
[708]	valid_0's rmse: 1659.84
[709]	valid_0's rmse: 1659.87
[710]	valid_0's rmse: 1659.8
[711]	valid_0's rmse: 1659.76
[712]	valid_0's rmse: 1659.77
[713]	valid_0's rmse: 1659.75
[714]	valid_0's rmse: 1659.58
[715]	valid_0's rmse: 1659.64
[716]	valid_0's rmse: 1659.64
[717]	valid_0's rmse: 1659.6
[718]	valid_0's rmse: 1659.56
[719]	valid_0's rmse: 1659.42
[720]	valid_0's rmse: 1659.35
[721]	valid_0's rmse: 1659.34
[722]	valid_0's rmse: 1659.2
[723]	valid_0's rmse: 1659.21
[724]	valid_0's rmse: 1659.23
[725]	valid_0's rmse: 1659.22
[726]	valid_0's rmse: 1659.18
[727]	valid_0's rmse: 1658.99
[728]	valid_0's rmse: 1658.96
[729]	valid_0's rmse: 1658.89
[730]	valid_0's rmse: 1658.89
[731]	valid_0's rmse: 1658.91
[732]	valid_0's rmse: 1658.92
[733]	valid_0's rmse: 1658.86
[734]	valid_0's rmse: 1658.83
[735]	valid_0's rmse: 1658.83
[736]	valid_0's rmse: 1658.87
[737]	valid_0's rmse: 1658.77
[738]	valid_0's rmse: 1658.67
[739]	valid_0's rmse: 1658.73
[740]	valid_0's rmse: 1658.76
[741]	valid_0's rmse: 1658.64
[742]	valid_0's rmse: 1658.66
[743]	valid_0's rmse: 1658.75
[744]	valid_0's rmse: 1658.68
[745]	valid_0's rmse: 1658.71
[746]	valid_0's rmse: 1658.59
[747]	valid_0's rmse: 1658.51
[748]	valid_0's rmse: 1658.48
[749]	valid_0's rmse: 1658.49
[750]	valid_0's rmse: 1658.45
[751]	valid_0's rmse: 1658.41
[752]	valid_0's rmse: 1658.32
[753]	valid_0's rmse: 1658.39
[754]	valid_0's rmse: 1658.31
[755]	valid_0's rmse: 1658.26
[756]	valid_0's rmse: 1658.08
[757]	valid_0's rmse: 1657.93
[758]	valid_0's rmse: 1657.93
[759]	valid_0's rmse: 1657.93
[760]	valid_0's rmse: 1657.89
[761]	valid_0's rmse: 1657.91
[762]	valid_0's rmse: 1657.88
[763]	valid_0's rmse: 1657.79
[764]	valid_0's rmse: 1657.64
[765]	valid_0's rmse: 1657.57
[766]	valid_0's rmse: 1657.49
[767]	valid_0's rmse: 1657.54
[768]	valid_0's rmse: 1657.45
[769]	valid_0's rmse: 1657.39
[770]	valid_0's rmse: 1657.3
[771]	valid_0's rmse: 1657.32
[772]	valid_0's rmse: 1657.27
[773]	valid_0's rmse: 1657.26
[774]	valid_0's rmse: 1657.27
[775]	valid_0's rmse: 1657.21
[776]	valid_0's rmse: 1657.06
[777]	valid_0's rmse: 1656.99
[778]	valid_0's rmse: 1657.02
[779]	valid_0's rmse: 1656.99
[780]	valid_0's rmse: 1656.9
[781]	valid_0's rmse: 1656.89
[782]	valid_0's rmse: 1656.86
[783]	valid_0's rmse: 1656.84
[784]	valid_0's rmse: 1656.75
[785]	valid_0's rmse: 1656.7
[786]	valid_0's rmse: 1656.64
[787]	valid_0's rmse: 1656.69
[788]	valid_0's rmse: 1656.64
[789]	valid_0's rmse: 1656.59
[790]	valid_0's rmse: 1656.56
[791]	valid_0's rmse: 1656.51
[792]	valid_0's rmse: 1656.37
[793]	valid_0's rmse: 1656.21
[794]	valid_0's rmse: 1656.07
[795]	valid_0's rmse: 1656.04
[796]	valid_0's rmse: 1656.03
[797]	valid_0's rmse: 1655.86
[798]	valid_0's rmse: 1655.92
[799]	valid_0's rmse: 1655.99
[800]	valid_0's rmse: 1655.98
[801]	valid_0's rmse: 1655.97
[802]	valid_0's rmse: 1655.98
[803]	valid_0's rmse: 1655.97
[804]	valid_0's rmse: 1656.06
[805]	valid_0's rmse: 1656.08
[806]	valid_0's rmse: 1656.11
[807]	valid_0's rmse: 1656.03
[808]	valid_0's rmse: 1655.96
[809]	valid_0's rmse: 1655.91
[810]	valid_0's rmse: 1655.78
[811]	valid_0's rmse: 1655.61
[812]	valid_0's rmse: 1655.64
[813]	valid_0's rmse: 1655.65
[814]	valid_0's rmse: 1655.68
[815]	valid_0's rmse: 1655.76
[816]	valid_0's rmse: 1655.73
[817]	valid_0's rmse: 1655.7
[818]	valid_0's rmse: 1655.62
[819]	valid_0's rmse: 1655.54
[820]	valid_0's rmse: 1655.43
[821]	valid_0's rmse: 1655.24
[822]	valid_0's rmse: 1655.18
[823]	valid_0's rmse: 1655.18
[824]	valid_0's rmse: 1655.11
[825]	valid_0's rmse: 1655.09
[826]	valid_0's rmse: 1655.03
[827]	valid_0's rmse: 1654.88
[828]	valid_0's rmse: 1654.97
[829]	valid_0's rmse: 1654.96
[830]	valid_0's rmse: 1655.04
[831]	valid_0's rmse: 1655.01
[832]	valid_0's rmse: 1655.05
[833]	valid_0's rmse: 1655.05
[834]	valid_0's rmse: 1655.06
[835]	valid_0's rmse: 1654.96
[836]	valid_0's rmse: 1654.9
[837]	valid_0's rmse: 1654.88
[838]	valid_0's rmse: 1654.83
[839]	valid_0's rmse: 1654.82
[840]	valid_0's rmse: 1654.79
[841]	valid_0's rmse: 1654.82
[842]	valid_0's rmse: 1654.78
[843]	valid_0's rmse: 1654.73
[844]	valid_0's rmse: 1654.74
[845]	valid_0's rmse: 1654.68
[846]	valid_0's rmse: 1654.6
[847]	valid_0's rmse: 1654.58
[848]	valid_0's rmse: 1654.59
[849]	valid_0's rmse: 1654.56
[850]	valid_0's rmse: 1654.54
[851]	valid_0's rmse: 1654.48
[852]	valid_0's rmse: 1654.48
[853]	valid_0's rmse: 1654.43
[854]	valid_0's rmse: 1654.4
[855]	valid_0's rmse: 1654.31
[856]	valid_0's rmse: 1654.26
[857]	valid_0's rmse: 1654.16
[858]	valid_0's rmse: 1653.99
[859]	valid_0's rmse: 1653.95
[860]	valid_0's rmse: 1653.95
[861]	valid_0's rmse: 1653.93
[862]	valid_0's rmse: 1653.8
[863]	valid_0's rmse: 1653.78
[864]	valid_0's rmse: 1653.8
[865]	valid_0's rmse: 1653.83
[866]	valid_0's rmse: 1653.81
[867]	valid_0's rmse: 1653.77
[868]	valid_0's rmse: 1653.74
[869]	valid_0's rmse: 1653.77

[870]	valid_0's rmse: 1653.84
[871]	valid_0's rmse: 1653.67
[872]	valid_0's rmse: 1653.54
[873]	valid_0's rmse: 1653.48
[874]	valid_0's rmse: 1653.48
[875]	valid_0's rmse: 1653.48
[876]	valid_0's rmse: 1653.51
[877]	valid_0's rmse: 1653.52
[878]	valid_0's rmse: 1653.48
[879]	valid_0's rmse: 1653.41
[880]	valid_0's rmse: 1653.4
[881]	valid_0's rmse: 1653.44
[882]	valid_0's rmse: 1653.44
[883]	valid_0's rmse: 1653.42
[884]	valid_0's rmse: 1653.41
[885]	valid_0's rmse: 1653.42
[886]	valid_0's rmse: 1653.4
[887]	valid_0's rmse: 1653.41
[888]	valid_0's rmse: 1653.39
[889]	valid_0's rmse: 1653.32
[890]	valid_0's rmse: 1653.23
[891]	valid_0's rmse: 1653.18
[892]	valid_0's rmse: 1653.17
[893]	valid_0's rmse: 1653.1
[894]	valid_0's rmse: 1653.1
[895]	valid_0's rmse: 1653.12
[896]	valid_0's rmse: 1653.11
[897]	valid_0's rmse: 1653.07
[898]	valid_0's rmse: 1653.06
[899]	valid_0's rmse: 1653.03
[900]	valid_0's rmse: 1652.95
[901]	valid_0's rmse: 1652.89
[902]	valid_0's rmse: 1652.87
[903]	valid_0's rmse: 1652.91
[904]	valid_0's rmse: 1652.86
[905]	valid_0's rmse: 1652.85
[906]	valid_0's rmse: 1652.78
[907]	valid_0's rmse: 1652.8
[908]	valid_0's rmse: 1652.75
[909]	valid_0's rmse: 1652.76
[910]	valid_0's rmse: 1652.8
[911]	valid_0's rmse: 1652.67
[912]	valid_0's rmse: 1652.6
[913]	valid_0's rmse: 1652.67
[914]	valid_0's rmse: 1652.65
[915]	valid_0's rmse: 1652.7
[916]	valid_0's rmse: 1652.66
[917]	valid_0's rmse: 1652.66
[918]	valid_0's rmse: 1652.67
[919]	valid_0's rmse: 1652.53
[920]	valid_0's rmse: 1652.52
[921]	valid_0's rmse: 1652.58
[922]	valid_0's rmse: 1652.6
[923]	valid_0's rmse: 1652.57
[924]	valid_0's rmse: 1652.55
[925]	valid_0's rmse: 1652.54
[926]	valid_0's rmse: 1652.54
[927]	valid_0's rmse: 1652.56
[928]	valid_0's rmse: 1652.47
[929]	valid_0's rmse: 1652.49
[930]	valid_0's rmse: 1652.46
[931]	valid_0's rmse: 1652.46
[932]	valid_0's rmse: 1652.37
[933]	valid_0's rmse: 1652.33
[934]	valid_0's rmse: 1652.37
[935]	valid_0's rmse: 1652.36
[936]	valid_0's rmse: 1652.33
[937]	valid_0's rmse: 1652.27
[938]	valid_0's rmse: 1652.27
[939]	valid_0's rmse: 1652.2
[940]	valid_0's rmse: 1652.2
[941]	valid_0's rmse: 1652.07
[942]	valid_0's rmse: 1652.01
[943]	valid_0's rmse: 1651.91
[944]	valid_0's rmse: 1651.93
[945]	valid_0's rmse: 1651.86
[946]	valid_0's rmse: 1651.85
[947]	valid_0's rmse: 1651.87
[948]	valid_0's rmse: 1651.8
[949]	valid_0's rmse: 1651.78
[950]	valid_0's rmse: 1651.79
[951]	valid_0's rmse: 1651.74
[952]	valid_0's rmse: 1651.75
[953]	valid_0's rmse: 1651.74
[954]	valid_0's rmse: 1651.72
[955]	valid_0's rmse: 1651.73
[956]	valid_0's rmse: 1651.7
[957]	valid_0's rmse: 1651.67
[958]	valid_0's rmse: 1651.67
[959]	valid_0's rmse: 1651.68
[960]	valid_0's rmse: 1651.65
[961]	valid_0's rmse: 1651.66
[962]	valid_0's rmse: 1651.68
[963]	valid_0's rmse: 1651.64
[964]	valid_0's rmse: 1651.6
[965]	valid_0's rmse: 1651.52
[966]	valid_0's rmse: 1651.56
[967]	valid_0's rmse: 1651.5
[968]	valid_0's rmse: 1651.43
[969]	valid_0's rmse: 1651.42
[970]	valid_0's rmse: 1651.4
[971]	valid_0's rmse: 1651.34
[972]	valid_0's rmse: 1651.32
[973]	valid_0's rmse: 1651.33
[974]	valid_0's rmse: 1651.25
[975]	valid_0's rmse: 1651.19
[976]	valid_0's rmse: 1651.15
[977]	valid_0's rmse: 1651.13
[978]	valid_0's rmse: 1651.13
[979]	valid_0's rmse: 1651.12
[980]	valid_0's rmse: 1651.07
[981]	valid_0's rmse: 1651.01
[982]	valid_0's rmse: 1650.96
[983]	valid_0's rmse: 1650.91
[984]	valid_0's rmse: 1650.9
[985]	valid_0's rmse: 1650.87
[986]	valid_0's rmse: 1650.85
[987]	valid_0's rmse: 1650.81
[988]	valid_0's rmse: 1650.82
[989]	valid_0's rmse: 1650.81
[990]	valid_0's rmse: 1650.81
[991]	valid_0's rmse: 1650.82
[992]	valid_0's rmse: 1650.77
[993]	valid_0's rmse: 1650.74
[994]	valid_0's rmse: 1650.71
[995]	valid_0's rmse: 1650.71
[996]	valid_0's rmse: 1650.74
[997]	valid_0's rmse: 1650.74
[998]	valid_0's rmse: 1650.66
[999]	valid_0's rmse: 1650.61
[1000]	valid_0's rmse: 1650.6
CPU times: user 29.1 s, sys: 1.7 s, total: 30.8 s
Wall time: 12.6 s

In [27]:
%%time

pred_train = model.predict(features_train)
pred_valid = model.predict(features_valid)
pred_test = model.predict(features_test)

CPU times: user 32.4 s, sys: 267 ms, total: 32.7 s
Wall time: 12.2 s

In [28]:
print("Train RMSE:", rmse(target_train, pred_train).round(5))
print("Valid RMSE:", rmse(target_valid, pred_valid).round(5))
print("Test RMSE: ", rmse(target_test, pred_test).round(5))

Train RMSE: 1410.9156
Valid RMSE: 1650.6038
Test RMSE:  1641.91689

In [29]:
%%time

import lightgbm as lgb

model = lgb.LGBMRegressor(num_iterations=1000, vebose=1, metric='rmse')
model.fit(features_train, target_train, 
          eval_set=(features_valid, target_valid))

/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:118: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))

[1]	valid_0's rmse: 4268.81
[2]	valid_0's rmse: 3988.72
[3]	valid_0's rmse: 3745.28
[4]	valid_0's rmse: 3533.96
[5]	valid_0's rmse: 3344.79
[6]	valid_0's rmse: 3180.15
[7]	valid_0's rmse: 3038.53
[8]	valid_0's rmse: 2913.76
[9]	valid_0's rmse: 2800.89
[10]	valid_0's rmse: 2703.65
[11]	valid_0's rmse: 2623.15
[12]	valid_0's rmse: 2548.09
[13]	valid_0's rmse: 2484.49
[14]	valid_0's rmse: 2428.51
[15]	valid_0's rmse: 2376.84
[16]	valid_0's rmse: 2330.6
[17]	valid_0's rmse: 2291.97
[18]	valid_0's rmse: 2256.88
[19]	valid_0's rmse: 2225.96
[20]	valid_0's rmse: 2197.94
[21]	valid_0's rmse: 2172.21
[22]	valid_0's rmse: 2146.89
[23]	valid_0's rmse: 2125.14
[24]	valid_0's rmse: 2105.92
[25]	valid_0's rmse: 2085.68
[26]	valid_0's rmse: 2069.76
[27]	valid_0's rmse: 2055.27
[28]	valid_0's rmse: 2041.37
[29]	valid_0's rmse: 2030.06
[30]	valid_0's rmse: 2019.88
[31]	valid_0's rmse: 2009.93
[32]	valid_0's rmse: 1999.63
[33]	valid_0's rmse: 1990.62
[34]	valid_0's rmse: 1984.02
[35]	valid_0's rmse: 1974.87
[36]	valid_0's rmse: 1967.7
[37]	valid_0's rmse: 1959.75
[38]	valid_0's rmse: 1952.77
[39]	valid_0's rmse: 1945.53
[40]	valid_0's rmse: 1940.22
[41]	valid_0's rmse: 1935.15
[42]	valid_0's rmse: 1930.31
[43]	valid_0's rmse: 1925.69
[44]	valid_0's rmse: 1920.23
[45]	valid_0's rmse: 1914.48
[46]	valid_0's rmse: 1910.76
[47]	valid_0's rmse: 1907.91
[48]	valid_0's rmse: 1903.88
[49]	valid_0's rmse: 1901.23
[50]	valid_0's rmse: 1898.23
[51]	valid_0's rmse: 1895.32
[52]	valid_0's rmse: 1890.67
[53]	valid_0's rmse: 1886.49
[54]	valid_0's rmse: 1884.32
[55]	valid_0's rmse: 1882.24
[56]	valid_0's rmse: 1878.8
[57]	valid_0's rmse: 1876.24
[58]	valid_0's rmse: 1874.59
[59]	valid_0's rmse: 1872.04
[60]	valid_0's rmse: 1869.56
[61]	valid_0's rmse: 1867.07
[62]	valid_0's rmse: 1865.36
[63]	valid_0's rmse: 1863.55
[64]	valid_0's rmse: 1860.67
[65]	valid_0's rmse: 1858.53
[66]	valid_0's rmse: 1857.16
[67]	valid_0's rmse: 1855.45
[68]	valid_0's rmse: 1854.57
[69]	valid_0's rmse: 1852.84
[70]	valid_0's rmse: 1851.13
[71]	valid_0's rmse: 1849.95
[72]	valid_0's rmse: 1847.76
[73]	valid_0's rmse: 1845.9
[74]	valid_0's rmse: 1843.51
[75]	valid_0's rmse: 1841.83
[76]	valid_0's rmse: 1840.85
[77]	valid_0's rmse: 1839.6
[78]	valid_0's rmse: 1838
[79]	valid_0's rmse: 1836.31
[80]	valid_0's rmse: 1835.64
[81]	valid_0's rmse: 1834.66
[82]	valid_0's rmse: 1833.94
[83]	valid_0's rmse: 1833.22
[84]	valid_0's rmse: 1831.78
[85]	valid_0's rmse: 1830.17
[86]	valid_0's rmse: 1829.24
[87]	valid_0's rmse: 1827.56
[88]	valid_0's rmse: 1826.05
[89]	valid_0's rmse: 1825.47
[90]	valid_0's rmse: 1824.95
[91]	valid_0's rmse: 1824.73
[92]	valid_0's rmse: 1823.32
[93]	valid_0's rmse: 1821.98
[94]	valid_0's rmse: 1821.06
[95]	valid_0's rmse: 1820.52
[96]	valid_0's rmse: 1819.76
[97]	valid_0's rmse: 1818.75
[98]	valid_0's rmse: 1818.16
[99]	valid_0's rmse: 1817.49
[100]	valid_0's rmse: 1817.17
[101]	valid_0's rmse: 1816.87
[102]	valid_0's rmse: 1816.05
[103]	valid_0's rmse: 1814.7
[104]	valid_0's rmse: 1813.73
[105]	valid_0's rmse: 1813.4
[106]	valid_0's rmse: 1812.8
[107]	valid_0's rmse: 1812.1
[108]	valid_0's rmse: 1811.6
[109]	valid_0's rmse: 1810.3
[110]	valid_0's rmse: 1809.89
[111]	valid_0's rmse: 1808.53
[112]	valid_0's rmse: 1807.53
[113]	valid_0's rmse: 1806.29
[114]	valid_0's rmse: 1805.48
[115]	valid_0's rmse: 1805.1
[116]	valid_0's rmse: 1804.19
[117]	valid_0's rmse: 1803.81
[118]	valid_0's rmse: 1803.18
[119]	valid_0's rmse: 1801.77
[120]	valid_0's rmse: 1800.9
[121]	valid_0's rmse: 1799.68
[122]	valid_0's rmse: 1799.28
[123]	valid_0's rmse: 1798.23
[124]	valid_0's rmse: 1797.86
[125]	valid_0's rmse: 1796.55
[126]	valid_0's rmse: 1795.92
[127]	valid_0's rmse: 1795.29
[128]	valid_0's rmse: 1794.2
[129]	valid_0's rmse: 1793.35
[130]	valid_0's rmse: 1792.47
[131]	valid_0's rmse: 1791.46
[132]	valid_0's rmse: 1790.82
[133]	valid_0's rmse: 1789.59
[134]	valid_0's rmse: 1789.06
[135]	valid_0's rmse: 1788.18
[136]	valid_0's rmse: 1787.21
[137]	valid_0's rmse: 1786.72
[138]	valid_0's rmse: 1785.67
[139]	valid_0's rmse: 1784.85
[140]	valid_0's rmse: 1784.6
[141]	valid_0's rmse: 1784.11
[142]	valid_0's rmse: 1783.57
[143]	valid_0's rmse: 1782.81
[144]	valid_0's rmse: 1782.25
[145]	valid_0's rmse: 1782.05
[146]	valid_0's rmse: 1781.28
[147]	valid_0's rmse: 1780.89
[148]	valid_0's rmse: 1780.43
[149]	valid_0's rmse: 1779.71
[150]	valid_0's rmse: 1779.15
[151]	valid_0's rmse: 1778.52
[152]	valid_0's rmse: 1778.08
[153]	valid_0's rmse: 1777.35
[154]	valid_0's rmse: 1776.6
[155]	valid_0's rmse: 1775.77
[156]	valid_0's rmse: 1775.27
[157]	valid_0's rmse: 1774.64
[158]	valid_0's rmse: 1774.37
[159]	valid_0's rmse: 1773.78
[160]	valid_0's rmse: 1773.8
[161]	valid_0's rmse: 1773.55
[162]	valid_0's rmse: 1773.27
[163]	valid_0's rmse: 1772.7
[164]	valid_0's rmse: 1771.93
[165]	valid_0's rmse: 1771.33
[166]	valid_0's rmse: 1770.6
[167]	valid_0's rmse: 1770.09
[168]	valid_0's rmse: 1769.67
[169]	valid_0's rmse: 1769.33
[170]	valid_0's rmse: 1768.82
[171]	valid_0's rmse: 1768.46
[172]	valid_0's rmse: 1767.79
[173]	valid_0's rmse: 1767.16
[174]	valid_0's rmse: 1766.77
[175]	valid_0's rmse: 1766.55
[176]	valid_0's rmse: 1765.85
[177]	valid_0's rmse: 1765.43
[178]	valid_0's rmse: 1764.94
[179]	valid_0's rmse: 1764.37
[180]	valid_0's rmse: 1764.25
[181]	valid_0's rmse: 1763.48
[182]	valid_0's rmse: 1763.25
[183]	valid_0's rmse: 1762.76
[184]	valid_0's rmse: 1762.27
[185]	valid_0's rmse: 1761.89
[186]	valid_0's rmse: 1761.29
[187]	valid_0's rmse: 1760.67
[188]	valid_0's rmse: 1760.55
[189]	valid_0's rmse: 1760.33
[190]	valid_0's rmse: 1760.04
[191]	valid_0's rmse: 1759.9
[192]	valid_0's rmse: 1759.49
[193]	valid_0's rmse: 1759.22
[194]	valid_0's rmse: 1759.04
[195]	valid_0's rmse: 1758.86
[196]	valid_0's rmse: 1758.62
[197]	valid_0's rmse: 1758.24
[198]	valid_0's rmse: 1757.9
[199]	valid_0's rmse: 1757.89
[200]	valid_0's rmse: 1757.82
[201]	valid_0's rmse: 1757.23
[202]	valid_0's rmse: 1756.46
[203]	valid_0's rmse: 1755.97
[204]	valid_0's rmse: 1755.53
[205]	valid_0's rmse: 1755.35
[206]	valid_0's rmse: 1755.3
[207]	valid_0's rmse: 1754.78
[208]	valid_0's rmse: 1754.65
[209]	valid_0's rmse: 1754.09
[210]	valid_0's rmse: 1753.93
[211]	valid_0's rmse: 1753.63
[212]	valid_0's rmse: 1753.26
[213]	valid_0's rmse: 1752.94
[214]	valid_0's rmse: 1752.49
[215]	valid_0's rmse: 1752.32
[216]	valid_0's rmse: 1751.74
[217]	valid_0's rmse: 1751.3
[218]	valid_0's rmse: 1750.71
[219]	valid_0's rmse: 1750.75
[220]	valid_0's rmse: 1750.57
[221]	valid_0's rmse: 1750.57
[222]	valid_0's rmse: 1750.3
[223]	valid_0's rmse: 1749.88
[224]	valid_0's rmse: 1749.47
[225]	valid_0's rmse: 1749.24
[226]	valid_0's rmse: 1748.85
[227]	valid_0's rmse: 1748.72
[228]	valid_0's rmse: 1748.5
[229]	valid_0's rmse: 1747.96
[230]	valid_0's rmse: 1747.56
[231]	valid_0's rmse: 1747.2
[232]	valid_0's rmse: 1747.14
[233]	valid_0's rmse: 1746.89
[234]	valid_0's rmse: 1746.48
[235]	valid_0's rmse: 1746.48
[236]	valid_0's rmse: 1746.29
[237]	valid_0's rmse: 1746.07
[238]	valid_0's rmse: 1745.85
[239]	valid_0's rmse: 1745.52
[240]	valid_0's rmse: 1745.18
[241]	valid_0's rmse: 1744.75
[242]	valid_0's rmse: 1744.62
[243]	valid_0's rmse: 1744.45
[244]	valid_0's rmse: 1744
[245]	valid_0's rmse: 1743.99
[246]	valid_0's rmse: 1743.82
[247]	valid_0's rmse: 1743.45
[248]	valid_0's rmse: 1743.13
[249]	valid_0's rmse: 1742.9
[250]	valid_0's rmse: 1742.61
[251]	valid_0's rmse: 1742.21
[252]	valid_0's rmse: 1742.19
[253]	valid_0's rmse: 1741.98
[254]	valid_0's rmse: 1741.92
[255]	valid_0's rmse: 1741.68
[256]	valid_0's rmse: 1741.29
[257]	valid_0's rmse: 1740.95
[258]	valid_0's rmse: 1740.85
[259]	valid_0's rmse: 1740.59
[260]	valid_0's rmse: 1740.43
[261]	valid_0's rmse: 1739.83
[262]	valid_0's rmse: 1739.43
[263]	valid_0's rmse: 1739.34
[264]	valid_0's rmse: 1738.71
[265]	valid_0's rmse: 1738.65
[266]	valid_0's rmse: 1738.72
[267]	valid_0's rmse: 1738.64
[268]	valid_0's rmse: 1738.3
[269]	valid_0's rmse: 1738.19
[270]	valid_0's rmse: 1737.77
[271]	valid_0's rmse: 1737.73
[272]	valid_0's rmse: 1737.69
[273]	valid_0's rmse: 1737.68
[274]	valid_0's rmse: 1737.6
[275]	valid_0's rmse: 1737.06
[276]	valid_0's rmse: 1737
[277]	valid_0's rmse: 1736.64
[278]	valid_0's rmse: 1736.54
[279]	valid_0's rmse: 1736.3
[280]	valid_0's rmse: 1735.99
[281]	valid_0's rmse: 1735.59
[282]	valid_0's rmse: 1735.45
[283]	valid_0's rmse: 1735.11
[284]	valid_0's rmse: 1734.94
[285]	valid_0's rmse: 1734.57
[286]	valid_0's rmse: 1734.21
[287]	valid_0's rmse: 1733.82
[288]	valid_0's rmse: 1733.66
[289]	valid_0's rmse: 1733.49
[290]	valid_0's rmse: 1733.31
[291]	valid_0's rmse: 1732.97
[292]	valid_0's rmse: 1732.76
[293]	valid_0's rmse: 1732.68
[294]	valid_0's rmse: 1732.54

[295]	valid_0's rmse: 1732.08
[296]	valid_0's rmse: 1731.86
[297]	valid_0's rmse: 1731.49
[298]	valid_0's rmse: 1731.35
[299]	valid_0's rmse: 1731.23
[300]	valid_0's rmse: 1730.98
[301]	valid_0's rmse: 1730.86
[302]	valid_0's rmse: 1730.91
[303]	valid_0's rmse: 1730.76
[304]	valid_0's rmse: 1730.6
[305]	valid_0's rmse: 1730.4
[306]	valid_0's rmse: 1730.18
[307]	valid_0's rmse: 1729.97
[308]	valid_0's rmse: 1729.85
[309]	valid_0's rmse: 1729.48
[310]	valid_0's rmse: 1729.15
[311]	valid_0's rmse: 1728.73
[312]	valid_0's rmse: 1728.68
[313]	valid_0's rmse: 1728.45
[314]	valid_0's rmse: 1728.38
[315]	valid_0's rmse: 1728.26
[316]	valid_0's rmse: 1727.92
[317]	valid_0's rmse: 1727.77
[318]	valid_0's rmse: 1727.64
[319]	valid_0's rmse: 1727.68
[320]	valid_0's rmse: 1727.31
[321]	valid_0's rmse: 1727.03
[322]	valid_0's rmse: 1726.88
[323]	valid_0's rmse: 1726.7
[324]	valid_0's rmse: 1726.6
[325]	valid_0's rmse: 1726.54
[326]	valid_0's rmse: 1726.36
[327]	valid_0's rmse: 1726.25
[328]	valid_0's rmse: 1726.14
[329]	valid_0's rmse: 1726.01
[330]	valid_0's rmse: 1726.03
[331]	valid_0's rmse: 1725.95
[332]	valid_0's rmse: 1725.72
[333]	valid_0's rmse: 1725.41
[334]	valid_0's rmse: 1725
[335]	valid_0's rmse: 1725
[336]	valid_0's rmse: 1724.71
[337]	valid_0's rmse: 1724.43
[338]	valid_0's rmse: 1724.26
[339]	valid_0's rmse: 1724.17
[340]	valid_0's rmse: 1723.88
[341]	valid_0's rmse: 1723.87
[342]	valid_0's rmse: 1723.54
[343]	valid_0's rmse: 1723.36
[344]	valid_0's rmse: 1723.17
[345]	valid_0's rmse: 1723.16
[346]	valid_0's rmse: 1722.84
[347]	valid_0's rmse: 1722.65
[348]	valid_0's rmse: 1722.56
[349]	valid_0's rmse: 1722.52
[350]	valid_0's rmse: 1722.41
[351]	valid_0's rmse: 1722.18
[352]	valid_0's rmse: 1722.13
[353]	valid_0's rmse: 1722.1
[354]	valid_0's rmse: 1721.8
[355]	valid_0's rmse: 1721.68
[356]	valid_0's rmse: 1721.47
[357]	valid_0's rmse: 1721.38
[358]	valid_0's rmse: 1721.1
[359]	valid_0's rmse: 1721.02
[360]	valid_0's rmse: 1720.95
[361]	valid_0's rmse: 1720.89
[362]	valid_0's rmse: 1720.85
[363]	valid_0's rmse: 1720.74
[364]	valid_0's rmse: 1720.57
[365]	valid_0's rmse: 1720.56
[366]	valid_0's rmse: 1720.59
[367]	valid_0's rmse: 1720.52
[368]	valid_0's rmse: 1720.38
[369]	valid_0's rmse: 1720.27
[370]	valid_0's rmse: 1720.19
[371]	valid_0's rmse: 1720.05
[372]	valid_0's rmse: 1720
[373]	valid_0's rmse: 1719.99
[374]	valid_0's rmse: 1719.87
[375]	valid_0's rmse: 1719.78
[376]	valid_0's rmse: 1719.49
[377]	valid_0's rmse: 1719.28
[378]	valid_0's rmse: 1719.12
[379]	valid_0's rmse: 1719.09
[380]	valid_0's rmse: 1719.11
[381]	valid_0's rmse: 1719.01
[382]	valid_0's rmse: 1718.65
[383]	valid_0's rmse: 1718.57
[384]	valid_0's rmse: 1718.54
[385]	valid_0's rmse: 1718.29
[386]	valid_0's rmse: 1718.14
[387]	valid_0's rmse: 1718
[388]	valid_0's rmse: 1717.75
[389]	valid_0's rmse: 1717.81
[390]	valid_0's rmse: 1717.64
[391]	valid_0's rmse: 1717.47
[392]	valid_0's rmse: 1717.1
[393]	valid_0's rmse: 1716.71
[394]	valid_0's rmse: 1716.52
[395]	valid_0's rmse: 1716.37
[396]	valid_0's rmse: 1716.39
[397]	valid_0's rmse: 1716.34
[398]	valid_0's rmse: 1716.18
[399]	valid_0's rmse: 1716.04
[400]	valid_0's rmse: 1715.98
[401]	valid_0's rmse: 1715.6
[402]	valid_0's rmse: 1715.44
[403]	valid_0's rmse: 1715.33
[404]	valid_0's rmse: 1715.03
[405]	valid_0's rmse: 1714.84
[406]	valid_0's rmse: 1714.8
[407]	valid_0's rmse: 1714.6
[408]	valid_0's rmse: 1714.41
[409]	valid_0's rmse: 1714.33
[410]	valid_0's rmse: 1714.31
[411]	valid_0's rmse: 1714.01
[412]	valid_0's rmse: 1713.77
[413]	valid_0's rmse: 1713.43
[414]	valid_0's rmse: 1713.31
[415]	valid_0's rmse: 1713.14
[416]	valid_0's rmse: 1713.08
[417]	valid_0's rmse: 1713.08
[418]	valid_0's rmse: 1712.91
[419]	valid_0's rmse: 1712.77
[420]	valid_0's rmse: 1712.74
[421]	valid_0's rmse: 1712.49
[422]	valid_0's rmse: 1712.13
[423]	valid_0's rmse: 1712.05
[424]	valid_0's rmse: 1711.7
[425]	valid_0's rmse: 1711.54
[426]	valid_0's rmse: 1711.53
[427]	valid_0's rmse: 1711.4
[428]	valid_0's rmse: 1711.2
[429]	valid_0's rmse: 1710.98
[430]	valid_0's rmse: 1710.75
[431]	valid_0's rmse: 1710.65
[432]	valid_0's rmse: 1710.54
[433]	valid_0's rmse: 1710.45
[434]	valid_0's rmse: 1710.43
[435]	valid_0's rmse: 1710.25
[436]	valid_0's rmse: 1710.27
[437]	valid_0's rmse: 1710.19
[438]	valid_0's rmse: 1710.12
[439]	valid_0's rmse: 1709.97
[440]	valid_0's rmse: 1709.76
[441]	valid_0's rmse: 1709.57
[442]	valid_0's rmse: 1709.55
[443]	valid_0's rmse: 1709.34
[444]	valid_0's rmse: 1709.27
[445]	valid_0's rmse: 1709.06
[446]	valid_0's rmse: 1708.87
[447]	valid_0's rmse: 1708.77
[448]	valid_0's rmse: 1708.6
[449]	valid_0's rmse: 1708.53
[450]	valid_0's rmse: 1708.34
[451]	valid_0's rmse: 1708.26
[452]	valid_0's rmse: 1708.21
[453]	valid_0's rmse: 1708.08
[454]	valid_0's rmse: 1707.89
[455]	valid_0's rmse: 1707.92
[456]	valid_0's rmse: 1707.72
[457]	valid_0's rmse: 1707.54
[458]	valid_0's rmse: 1707.47
[459]	valid_0's rmse: 1707.33
[460]	valid_0's rmse: 1707.17
[461]	valid_0's rmse: 1706.95
[462]	valid_0's rmse: 1706.82
[463]	valid_0's rmse: 1706.84
[464]	valid_0's rmse: 1706.77
[465]	valid_0's rmse: 1706.8
[466]	valid_0's rmse: 1706.72
[467]	valid_0's rmse: 1706.57
[468]	valid_0's rmse: 1706.6
[469]	valid_0's rmse: 1706.44
[470]	valid_0's rmse: 1706.35
[471]	valid_0's rmse: 1706.52
[472]	valid_0's rmse: 1706.37
[473]	valid_0's rmse: 1706.3
[474]	valid_0's rmse: 1706.21
[475]	valid_0's rmse: 1706.2
[476]	valid_0's rmse: 1706.07
[477]	valid_0's rmse: 1705.81
[478]	valid_0's rmse: 1705.78
[479]	valid_0's rmse: 1705.69
[480]	valid_0's rmse: 1705.49
[481]	valid_0's rmse: 1705.35
[482]	valid_0's rmse: 1705.35
[483]	valid_0's rmse: 1705.29
[484]	valid_0's rmse: 1705.25
[485]	valid_0's rmse: 1705.29
[486]	valid_0's rmse: 1705.16
[487]	valid_0's rmse: 1704.96
[488]	valid_0's rmse: 1704.88
[489]	valid_0's rmse: 1704.78
[490]	valid_0's rmse: 1704.69
[491]	valid_0's rmse: 1704.53
[492]	valid_0's rmse: 1704.54
[493]	valid_0's rmse: 1704.49
[494]	valid_0's rmse: 1704.34
[495]	valid_0's rmse: 1704.27
[496]	valid_0's rmse: 1704.32
[497]	valid_0's rmse: 1704.31
[498]	valid_0's rmse: 1704.29
[499]	valid_0's rmse: 1704.26
[500]	valid_0's rmse: 1704.17
[501]	valid_0's rmse: 1704.06
[502]	valid_0's rmse: 1703.87
[503]	valid_0's rmse: 1703.86
[504]	valid_0's rmse: 1703.78
[505]	valid_0's rmse: 1703.54
[506]	valid_0's rmse: 1703.54
[507]	valid_0's rmse: 1703.48
[508]	valid_0's rmse: 1703.21
[509]	valid_0's rmse: 1703.15
[510]	valid_0's rmse: 1702.93
[511]	valid_0's rmse: 1702.92
[512]	valid_0's rmse: 1702.69
[513]	valid_0's rmse: 1702.47
[514]	valid_0's rmse: 1702.5
[515]	valid_0's rmse: 1702.38
[516]	valid_0's rmse: 1702.14
[517]	valid_0's rmse: 1701.95
[518]	valid_0's rmse: 1701.81
[519]	valid_0's rmse: 1701.77
[520]	valid_0's rmse: 1701.53
[521]	valid_0's rmse: 1701.41
[522]	valid_0's rmse: 1701.33
[523]	valid_0's rmse: 1701.3
[524]	valid_0's rmse: 1701.19
[525]	valid_0's rmse: 1701.08
[526]	valid_0's rmse: 1701.02
[527]	valid_0's rmse: 1700.98
[528]	valid_0's rmse: 1700.92
[529]	valid_0's rmse: 1700.75
[530]	valid_0's rmse: 1700.67
[531]	valid_0's rmse: 1700.55
[532]	valid_0's rmse: 1700.48
[533]	valid_0's rmse: 1700.43
[534]	valid_0's rmse: 1700.22
[535]	valid_0's rmse: 1700.13
[536]	valid_0's rmse: 1699.92
[537]	valid_0's rmse: 1699.64
[538]	valid_0's rmse: 1699.65
[539]	valid_0's rmse: 1699.5
[540]	valid_0's rmse: 1699.42
[541]	valid_0's rmse: 1699.32
[542]	valid_0's rmse: 1699.25
[543]	valid_0's rmse: 1699.18
[544]	valid_0's rmse: 1699.24
[545]	valid_0's rmse: 1699.15
[546]	valid_0's rmse: 1699.13
[547]	valid_0's rmse: 1698.9
[548]	valid_0's rmse: 1698.86
[549]	valid_0's rmse: 1698.65
[550]	valid_0's rmse: 1698.51
[551]	valid_0's rmse: 1698.4
[552]	valid_0's rmse: 1698.23
[553]	valid_0's rmse: 1698.1
[554]	valid_0's rmse: 1698
[555]	valid_0's rmse: 1697.98
[556]	valid_0's rmse: 1697.85
[557]	valid_0's rmse: 1697.75
[558]	valid_0's rmse: 1697.71
[559]	valid_0's rmse: 1697.65
[560]	valid_0's rmse: 1697.47
[561]	valid_0's rmse: 1697.34
[562]	valid_0's rmse: 1697.29
[563]	valid_0's rmse: 1697.17
[564]	valid_0's rmse: 1697.14
[565]	valid_0's rmse: 1697.16
[566]	valid_0's rmse: 1697.05
[567]	valid_0's rmse: 1696.82
[568]	valid_0's rmse: 1696.72
[569]	valid_0's rmse: 1696.66
[570]	valid_0's rmse: 1696.66
[571]	valid_0's rmse: 1696.62
[572]	valid_0's rmse: 1696.53
[573]	valid_0's rmse: 1696.46
[574]	valid_0's rmse: 1696.48
[575]	valid_0's rmse: 1696.48
[576]	valid_0's rmse: 1696.31
[577]	valid_0's rmse: 1696.32
[578]	valid_0's rmse: 1696.27
[579]	valid_0's rmse: 1696.33
[580]	valid_0's rmse: 1696.29
[581]	valid_0's rmse: 1696.22
[582]	valid_0's rmse: 1696.35
[583]	valid_0's rmse: 1696.38
[584]	valid_0's rmse: 1696.26
[585]	valid_0's rmse: 1696.14
[586]	valid_0's rmse: 1696.09
[587]	valid_0's rmse: 1695.94
[588]	valid_0's rmse: 1695.95
[589]	valid_0's rmse: 1695.77
[590]	valid_0's rmse: 1695.74
[591]	valid_0's rmse: 1695.72
[592]	valid_0's rmse: 1695.66
[593]	valid_0's rmse: 1695.56
[594]	valid_0's rmse: 1695.39

[595]	valid_0's rmse: 1695.29
[596]	valid_0's rmse: 1695.11
[597]	valid_0's rmse: 1695.12
[598]	valid_0's rmse: 1695.03
[599]	valid_0's rmse: 1694.96
[600]	valid_0's rmse: 1694.92
[601]	valid_0's rmse: 1694.83
[602]	valid_0's rmse: 1694.87
[603]	valid_0's rmse: 1694.68
[604]	valid_0's rmse: 1694.6
[605]	valid_0's rmse: 1694.45
[606]	valid_0's rmse: 1694.43
[607]	valid_0's rmse: 1694.49
[608]	valid_0's rmse: 1694.53
[609]	valid_0's rmse: 1694.55
[610]	valid_0's rmse: 1694.44
[611]	valid_0's rmse: 1694.41
[612]	valid_0's rmse: 1694.35
[613]	valid_0's rmse: 1694.24
[614]	valid_0's rmse: 1694.17
[615]	valid_0's rmse: 1694.07
[616]	valid_0's rmse: 1694.12
[617]	valid_0's rmse: 1694.15
[618]	valid_0's rmse: 1693.9
[619]	valid_0's rmse: 1693.9
[620]	valid_0's rmse: 1693.89
[621]	valid_0's rmse: 1693.86
[622]	valid_0's rmse: 1693.67
[623]	valid_0's rmse: 1693.49
[624]	valid_0's rmse: 1693.46
[625]	valid_0's rmse: 1693.37
[626]	valid_0's rmse: 1693.32
[627]	valid_0's rmse: 1693.33
[628]	valid_0's rmse: 1693.09
[629]	valid_0's rmse: 1693.01
[630]	valid_0's rmse: 1692.84
[631]	valid_0's rmse: 1692.8
[632]	valid_0's rmse: 1692.61
[633]	valid_0's rmse: 1692.62
[634]	valid_0's rmse: 1692.66
[635]	valid_0's rmse: 1692.46
[636]	valid_0's rmse: 1692.34
[637]	valid_0's rmse: 1692.32
[638]	valid_0's rmse: 1692.4
[639]	valid_0's rmse: 1692.37
[640]	valid_0's rmse: 1692.31
[641]	valid_0's rmse: 1692.23
[642]	valid_0's rmse: 1692.19
[643]	valid_0's rmse: 1692.14
[644]	valid_0's rmse: 1692.07
[645]	valid_0's rmse: 1692.02
[646]	valid_0's rmse: 1691.98
[647]	valid_0's rmse: 1691.87
[648]	valid_0's rmse: 1691.82
[649]	valid_0's rmse: 1691.78
[650]	valid_0's rmse: 1691.69
[651]	valid_0's rmse: 1691.61
[652]	valid_0's rmse: 1691.38
[653]	valid_0's rmse: 1691.27
[654]	valid_0's rmse: 1691.19
[655]	valid_0's rmse: 1691.03
[656]	valid_0's rmse: 1691
[657]	valid_0's rmse: 1690.98
[658]	valid_0's rmse: 1690.85
[659]	valid_0's rmse: 1690.77
[660]	valid_0's rmse: 1690.65
[661]	valid_0's rmse: 1690.55
[662]	valid_0's rmse: 1690.53
[663]	valid_0's rmse: 1690.44
[664]	valid_0's rmse: 1690.49
[665]	valid_0's rmse: 1690.43
[666]	valid_0's rmse: 1690.38
[667]	valid_0's rmse: 1690.27
[668]	valid_0's rmse: 1690.15
[669]	valid_0's rmse: 1690.11
[670]	valid_0's rmse: 1690.01
[671]	valid_0's rmse: 1690.07
[672]	valid_0's rmse: 1690.02
[673]	valid_0's rmse: 1689.96
[674]	valid_0's rmse: 1689.95
[675]	valid_0's rmse: 1689.94
[676]	valid_0's rmse: 1689.93
[677]	valid_0's rmse: 1689.86
[678]	valid_0's rmse: 1689.8
[679]	valid_0's rmse: 1689.8
[680]	valid_0's rmse: 1689.61
[681]	valid_0's rmse: 1689.53
[682]	valid_0's rmse: 1689.5
[683]	valid_0's rmse: 1689.48
[684]	valid_0's rmse: 1689.46
[685]	valid_0's rmse: 1689.4
[686]	valid_0's rmse: 1689.36
[687]	valid_0's rmse: 1689.36
[688]	valid_0's rmse: 1689.23
[689]	valid_0's rmse: 1689.13
[690]	valid_0's rmse: 1689.18
[691]	valid_0's rmse: 1689.1
[692]	valid_0's rmse: 1689.05
[693]	valid_0's rmse: 1689
[694]	valid_0's rmse: 1688.87
[695]	valid_0's rmse: 1688.77
[696]	valid_0's rmse: 1688.67
[697]	valid_0's rmse: 1688.64
[698]	valid_0's rmse: 1688.55
[699]	valid_0's rmse: 1688.5
[700]	valid_0's rmse: 1688.48
[701]	valid_0's rmse: 1688.51
[702]	valid_0's rmse: 1688.33
[703]	valid_0's rmse: 1688.34
[704]	valid_0's rmse: 1688.25
[705]	valid_0's rmse: 1688.16
[706]	valid_0's rmse: 1688.12
[707]	valid_0's rmse: 1688.06
[708]	valid_0's rmse: 1688.05
[709]	valid_0's rmse: 1687.9
[710]	valid_0's rmse: 1687.88
[711]	valid_0's rmse: 1687.75
[712]	valid_0's rmse: 1687.71
[713]	valid_0's rmse: 1687.6
[714]	valid_0's rmse: 1687.47
[715]	valid_0's rmse: 1687.45
[716]	valid_0's rmse: 1687.34
[717]	valid_0's rmse: 1687.28
[718]	valid_0's rmse: 1687.29
[719]	valid_0's rmse: 1687.21
[720]	valid_0's rmse: 1687.09
[721]	valid_0's rmse: 1686.98
[722]	valid_0's rmse: 1686.99
[723]	valid_0's rmse: 1686.89
[724]	valid_0's rmse: 1686.86
[725]	valid_0's rmse: 1686.79
[726]	valid_0's rmse: 1686.83
[727]	valid_0's rmse: 1686.87
[728]	valid_0's rmse: 1686.86
[729]	valid_0's rmse: 1686.75
[730]	valid_0's rmse: 1686.7
[731]	valid_0's rmse: 1686.7
[732]	valid_0's rmse: 1686.75
[733]	valid_0's rmse: 1686.71
[734]	valid_0's rmse: 1686.57
[735]	valid_0's rmse: 1686.42
[736]	valid_0's rmse: 1686.29
[737]	valid_0's rmse: 1686.21
[738]	valid_0's rmse: 1686.13
[739]	valid_0's rmse: 1685.99
[740]	valid_0's rmse: 1685.9
[741]	valid_0's rmse: 1685.79
[742]	valid_0's rmse: 1685.77
[743]	valid_0's rmse: 1685.64
[744]	valid_0's rmse: 1685.5
[745]	valid_0's rmse: 1685.5
[746]	valid_0's rmse: 1685.38
[747]	valid_0's rmse: 1685.34
[748]	valid_0's rmse: 1685.31
[749]	valid_0's rmse: 1685.06
[750]	valid_0's rmse: 1684.97
[751]	valid_0's rmse: 1685.08
[752]	valid_0's rmse: 1684.98
[753]	valid_0's rmse: 1684.97
[754]	valid_0's rmse: 1684.9
[755]	valid_0's rmse: 1684.87
[756]	valid_0's rmse: 1684.7
[757]	valid_0's rmse: 1684.65
[758]	valid_0's rmse: 1684.55
[759]	valid_0's rmse: 1684.51
[760]	valid_0's rmse: 1684.45
[761]	valid_0's rmse: 1684.3
[762]	valid_0's rmse: 1684.15
[763]	valid_0's rmse: 1684.17
[764]	valid_0's rmse: 1684.22
[765]	valid_0's rmse: 1684.13
[766]	valid_0's rmse: 1684.07
[767]	valid_0's rmse: 1684.08
[768]	valid_0's rmse: 1684.05
[769]	valid_0's rmse: 1684.06
[770]	valid_0's rmse: 1684.08
[771]	valid_0's rmse: 1684.07
[772]	valid_0's rmse: 1683.94
[773]	valid_0's rmse: 1683.88
[774]	valid_0's rmse: 1683.86
[775]	valid_0's rmse: 1683.78
[776]	valid_0's rmse: 1683.82
[777]	valid_0's rmse: 1683.85
[778]	valid_0's rmse: 1683.86
[779]	valid_0's rmse: 1683.72
[780]	valid_0's rmse: 1683.71
[781]	valid_0's rmse: 1683.68
[782]	valid_0's rmse: 1683.61
[783]	valid_0's rmse: 1683.61
[784]	valid_0's rmse: 1683.62
[785]	valid_0's rmse: 1683.4
[786]	valid_0's rmse: 1683.38
[787]	valid_0's rmse: 1683.35
[788]	valid_0's rmse: 1683.27
[789]	valid_0's rmse: 1683.24
[790]	valid_0's rmse: 1683.18
[791]	valid_0's rmse: 1683.19
[792]	valid_0's rmse: 1683.1
[793]	valid_0's rmse: 1682.8
[794]	valid_0's rmse: 1682.66
[795]	valid_0's rmse: 1682.63
[796]	valid_0's rmse: 1682.61
[797]	valid_0's rmse: 1682.51
[798]	valid_0's rmse: 1682.39
[799]	valid_0's rmse: 1682.33
[800]	valid_0's rmse: 1682.24
[801]	valid_0's rmse: 1682
[802]	valid_0's rmse: 1682.02
[803]	valid_0's rmse: 1681.96
[804]	valid_0's rmse: 1681.92
[805]	valid_0's rmse: 1681.91
[806]	valid_0's rmse: 1681.75
[807]	valid_0's rmse: 1681.67
[808]	valid_0's rmse: 1681.69
[809]	valid_0's rmse: 1681.67
[810]	valid_0's rmse: 1681.62
[811]	valid_0's rmse: 1681.61
[812]	valid_0's rmse: 1681.61
[813]	valid_0's rmse: 1681.48
[814]	valid_0's rmse: 1681.47
[815]	valid_0's rmse: 1681.41
[816]	valid_0's rmse: 1681.47
[817]	valid_0's rmse: 1681.4
[818]	valid_0's rmse: 1681.32
[819]	valid_0's rmse: 1681.16
[820]	valid_0's rmse: 1681.19
[821]	valid_0's rmse: 1681.13
[822]	valid_0's rmse: 1680.97
[823]	valid_0's rmse: 1680.98
[824]	valid_0's rmse: 1680.93
[825]	valid_0's rmse: 1680.88
[826]	valid_0's rmse: 1680.85
[827]	valid_0's rmse: 1680.81
[828]	valid_0's rmse: 1680.71
[829]	valid_0's rmse: 1680.74
[830]	valid_0's rmse: 1680.72
[831]	valid_0's rmse: 1680.63
[832]	valid_0's rmse: 1680.65
[833]	valid_0's rmse: 1680.64
[834]	valid_0's rmse: 1680.6
[835]	valid_0's rmse: 1680.53
[836]	valid_0's rmse: 1680.53
[837]	valid_0's rmse: 1680.51
[838]	valid_0's rmse: 1680.46
[839]	valid_0's rmse: 1680.43
[840]	valid_0's rmse: 1680.39
[841]	valid_0's rmse: 1680.33
[842]	valid_0's rmse: 1680.38
[843]	valid_0's rmse: 1680.36
[844]	valid_0's rmse: 1680.31
[845]	valid_0's rmse: 1680.29
[846]	valid_0's rmse: 1680.21
[847]	valid_0's rmse: 1680.22
[848]	valid_0's rmse: 1680.21
[849]	valid_0's rmse: 1680.18
[850]	valid_0's rmse: 1680.14
[851]	valid_0's rmse: 1680.09
[852]	valid_0's rmse: 1680
[853]	valid_0's rmse: 1679.92
[854]	valid_0's rmse: 1679.86
[855]	valid_0's rmse: 1679.85
[856]	valid_0's rmse: 1679.81
[857]	valid_0's rmse: 1679.72
[858]	valid_0's rmse: 1679.7
[859]	valid_0's rmse: 1679.68
[860]	valid_0's rmse: 1679.59
[861]	valid_0's rmse: 1679.54
[862]	valid_0's rmse: 1679.45
[863]	valid_0's rmse: 1679.32
[864]	valid_0's rmse: 1679.28
[865]	valid_0's rmse: 1679.21
[866]	valid_0's rmse: 1679.21
[867]	valid_0's rmse: 1679.22
[868]	valid_0's rmse: 1679.19
[869]	valid_0's rmse: 1678.94
[870]	valid_0's rmse: 1678.93
[871]	valid_0's rmse: 1678.93
[872]	valid_0's rmse: 1678.81
[873]	valid_0's rmse: 1678.8
[874]	valid_0's rmse: 1678.87
[875]	valid_0's rmse: 1678.63
[876]	valid_0's rmse: 1678.62
[877]	valid_0's rmse: 1678.56
[878]	valid_0's rmse: 1678.45

[879]	valid_0's rmse: 1678.38
[880]	valid_0's rmse: 1678.37
[881]	valid_0's rmse: 1678.4
[882]	valid_0's rmse: 1678.33
[883]	valid_0's rmse: 1678.34
[884]	valid_0's rmse: 1678.24
[885]	valid_0's rmse: 1678.22
[886]	valid_0's rmse: 1678.21
[887]	valid_0's rmse: 1678.19
[888]	valid_0's rmse: 1678.19
[889]	valid_0's rmse: 1678.14
[890]	valid_0's rmse: 1678.12
[891]	valid_0's rmse: 1678.09
[892]	valid_0's rmse: 1678.1
[893]	valid_0's rmse: 1678.06
[894]	valid_0's rmse: 1678.07
[895]	valid_0's rmse: 1678
[896]	valid_0's rmse: 1677.98
[897]	valid_0's rmse: 1677.79
[898]	valid_0's rmse: 1677.76
[899]	valid_0's rmse: 1677.71
[900]	valid_0's rmse: 1677.73
[901]	valid_0's rmse: 1677.69
[902]	valid_0's rmse: 1677.65
[903]	valid_0's rmse: 1677.67
[904]	valid_0's rmse: 1677.55
[905]	valid_0's rmse: 1677.45
[906]	valid_0's rmse: 1677.41
[907]	valid_0's rmse: 1677.48
[908]	valid_0's rmse: 1677.46
[909]	valid_0's rmse: 1677.49
[910]	valid_0's rmse: 1677.46
[911]	valid_0's rmse: 1677.43
[912]	valid_0's rmse: 1677.46
[913]	valid_0's rmse: 1677.3
[914]	valid_0's rmse: 1677.21
[915]	valid_0's rmse: 1677.11
[916]	valid_0's rmse: 1677.14
[917]	valid_0's rmse: 1677.02
[918]	valid_0's rmse: 1676.99
[919]	valid_0's rmse: 1677.06
[920]	valid_0's rmse: 1677.12
[921]	valid_0's rmse: 1677.13
[922]	valid_0's rmse: 1677.14
[923]	valid_0's rmse: 1677.16
[924]	valid_0's rmse: 1677.17
[925]	valid_0's rmse: 1677.15
[926]	valid_0's rmse: 1677.17
[927]	valid_0's rmse: 1677.15
[928]	valid_0's rmse: 1677.13
[929]	valid_0's rmse: 1677.01
[930]	valid_0's rmse: 1676.99
[931]	valid_0's rmse: 1677.02
[932]	valid_0's rmse: 1676.97
[933]	valid_0's rmse: 1676.99
[934]	valid_0's rmse: 1676.96
[935]	valid_0's rmse: 1676.87
[936]	valid_0's rmse: 1676.78
[937]	valid_0's rmse: 1676.69
[938]	valid_0's rmse: 1676.64
[939]	valid_0's rmse: 1676.56
[940]	valid_0's rmse: 1676.51
[941]	valid_0's rmse: 1676.44
[942]	valid_0's rmse: 1676.39
[943]	valid_0's rmse: 1676.33
[944]	valid_0's rmse: 1676.31
[945]	valid_0's rmse: 1676.22
[946]	valid_0's rmse: 1676.21
[947]	valid_0's rmse: 1676.15
[948]	valid_0's rmse: 1676.1
[949]	valid_0's rmse: 1676.07
[950]	valid_0's rmse: 1676.08
[951]	valid_0's rmse: 1675.93
[952]	valid_0's rmse: 1675.98
[953]	valid_0's rmse: 1675.93
[954]	valid_0's rmse: 1675.95
[955]	valid_0's rmse: 1675.9
[956]	valid_0's rmse: 1675.88
[957]	valid_0's rmse: 1675.88
[958]	valid_0's rmse: 1675.86
[959]	valid_0's rmse: 1675.87
[960]	valid_0's rmse: 1675.87
[961]	valid_0's rmse: 1675.77
[962]	valid_0's rmse: 1675.9
[963]	valid_0's rmse: 1675.9
[964]	valid_0's rmse: 1675.89
[965]	valid_0's rmse: 1675.82
[966]	valid_0's rmse: 1675.75
[967]	valid_0's rmse: 1675.73
[968]	valid_0's rmse: 1675.77
[969]	valid_0's rmse: 1675.79
[970]	valid_0's rmse: 1675.78
[971]	valid_0's rmse: 1675.76
[972]	valid_0's rmse: 1675.73
[973]	valid_0's rmse: 1675.54
[974]	valid_0's rmse: 1675.52
[975]	valid_0's rmse: 1675.6
[976]	valid_0's rmse: 1675.49
[977]	valid_0's rmse: 1675.42
[978]	valid_0's rmse: 1675.37
[979]	valid_0's rmse: 1675.42
[980]	valid_0's rmse: 1675.37
[981]	valid_0's rmse: 1675.36
[982]	valid_0's rmse: 1675.33
[983]	valid_0's rmse: 1675.28
[984]	valid_0's rmse: 1675.35
[985]	valid_0's rmse: 1675.31
[986]	valid_0's rmse: 1675.34
[987]	valid_0's rmse: 1675.29
[988]	valid_0's rmse: 1675.22
[989]	valid_0's rmse: 1675.2
[990]	valid_0's rmse: 1675
[991]	valid_0's rmse: 1674.87
[992]	valid_0's rmse: 1674.81
[993]	valid_0's rmse: 1674.78
[994]	valid_0's rmse: 1674.65
[995]	valid_0's rmse: 1674.55
[996]	valid_0's rmse: 1674.52
[997]	valid_0's rmse: 1674.43
[998]	valid_0's rmse: 1674.41
[999]	valid_0's rmse: 1674.37
[1000]	valid_0's rmse: 1674.35
CPU times: user 28.1 s, sys: 1.11 s, total: 29.2 s
Wall time: 9.59 s

In [30]:
%%time

pred_train = model.predict(features_train)
pred_valid = model.predict(features_valid)
pred_test = model.predict(features_test)

CPU times: user 25.6 s, sys: 219 ms, total: 25.8 s
Wall time: 9.01 s

In [31]:
print("Train RMSE:", rmse(target_train, pred_train).round(5))
print("Valid RMSE:", rmse(target_valid, pred_valid).round(5))
print("Test RMSE: ", rmse(target_test, pred_test).round(5))

Train RMSE: 1460.69366
Valid RMSE: 1674.35245
Test RMSE:  1657.71951

**Gradient boosting CatBoost**

In [32]:
%%time

from catboost import CatBoostRegressor

model = CatBoostRegressor(iterations=1000,
                          learning_rate=0.1,
                          cat_features=categorical_features,
                          metric_period=50)
model.fit(features_train, target_train, 
          eval_set=(features_valid, target_valid))

0:	learn: 6040.0153813	test: 6028.7735266	best: 6028.7735266 (0)	total: 375ms	remaining: 6m 14s
50:	learn: 1977.2979179	test: 1975.1906172	best: 1975.1906172 (50)	total: 12s	remaining: 3m 43s
100:	learn: 1878.4069481	test: 1884.6503300	best: 1884.6503300 (100)	total: 23.2s	remaining: 3m 26s
150:	learn: 1831.3260017	test: 1844.0234889	best: 1844.0234889 (150)	total: 33.8s	remaining: 3m 10s
200:	learn: 1801.3435718	test: 1819.9635823	best: 1819.9635823 (200)	total: 42.5s	remaining: 2m 48s
250:	learn: 1779.9786481	test: 1802.8899208	best: 1802.8899208 (250)	total: 53.3s	remaining: 2m 38s
300:	learn: 1765.2174567	test: 1793.7512949	best: 1793.7512949 (300)	total: 1m 2s	remaining: 2m 25s
350:	learn: 1752.0341631	test: 1785.2491052	best: 1785.2491052 (350)	total: 1m 14s	remaining: 2m 17s
400:	learn: 1739.9659470	test: 1776.7791369	best: 1776.7791369 (400)	total: 1m 24s	remaining: 2m 6s
450:	learn: 1730.1814284	test: 1770.9604790	best: 1770.9604790 (450)	total: 1m 35s	remaining: 1m 55s
500:	learn: 1720.3683917	test: 1765.6740943	best: 1765.6740943 (500)	total: 1m 46s	remaining: 1m 45s
550:	learn: 1711.3538386	test: 1760.2745146	best: 1760.2745146 (550)	total: 1m 57s	remaining: 1m 35s
600:	learn: 1704.6788228	test: 1757.2645124	best: 1757.2645124 (600)	total: 2m 8s	remaining: 1m 25s
650:	learn: 1697.6674292	test: 1753.8089566	best: 1753.8089566 (650)	total: 2m 20s	remaining: 1m 15s
700:	learn: 1690.4076748	test: 1750.1658990	best: 1750.1658990 (700)	total: 2m 31s	remaining: 1m 4s
750:	learn: 1684.9493646	test: 1747.8720907	best: 1747.8720907 (750)	total: 2m 43s	remaining: 54.1s
800:	learn: 1679.2303675	test: 1745.3516539	best: 1745.3516539 (800)	total: 2m 54s	remaining: 43.4s
850:	learn: 1673.9441172	test: 1743.1627713	best: 1743.1627713 (850)	total: 3m 4s	remaining: 32.4s
900:	learn: 1668.0728285	test: 1740.7308351	best: 1740.7308351 (900)	total: 3m 18s	remaining: 21.8s
950:	learn: 1662.6327205	test: 1738.4668608	best: 1738.4668608 (950)	total: 3m 27s	remaining: 10.7s
999:	learn: 1657.5970718	test: 1736.3486066	best: 1736.3486066 (999)	total: 3m 36s	remaining: 0us

bestTest = 1736.348607
bestIteration = 999

CPU times: user 9min 4s, sys: 52.9 s, total: 9min 57s
Wall time: 3min 39s

In [33]:
%%time

pred_train = model.predict(features_train)
pred_valid = model.predict(features_valid)
pred_test = model.predict(features_test)

CPU times: user 7.37 s, sys: 98.8 ms, total: 7.47 s
Wall time: 4.45 s

In [34]:
print("Train RMSE:", rmse(target_train, pred_train).round(5))
print("Valid RMSE:", rmse(target_valid, pred_valid).round(5))
print("Test RMSE: ", rmse(target_test, pred_test).round(5))

Train RMSE: 1662.79723
Valid RMSE: 1736.34861
Test RMSE:  1723.89198

In [35]:
%%time

from catboost import CatBoostRegressor

model = CatBoostRegressor(iterations=1000,
                          learning_rate=0.1,
                          metric_period=50)
model.fit(features_train, target_train, 
          eval_set=(features_valid, target_valid))

0:	learn: 6049.6962500	test: 6038.3281568	best: 6038.3281568 (0)	total: 39.5ms	remaining: 39.5s
50:	learn: 2038.2343375	test: 2040.3568612	best: 2040.3568612 (50)	total: 1.42s	remaining: 26.4s
100:	learn: 1921.3669448	test: 1929.7341784	best: 1929.7341784 (100)	total: 3.19s	remaining: 28.4s
150:	learn: 1867.7983558	test: 1881.4822962	best: 1881.4822962 (150)	total: 4.78s	remaining: 26.9s
200:	learn: 1835.9848684	test: 1854.2801221	best: 1854.2801221 (200)	total: 6.48s	remaining: 25.8s
250:	learn: 1810.6084616	test: 1833.5939341	best: 1833.5939341 (250)	total: 7.79s	remaining: 23.2s
300:	learn: 1790.0584162	test: 1818.6976854	best: 1818.6976854 (300)	total: 9.3s	remaining: 21.6s
350:	learn: 1776.3028147	test: 1809.7277425	best: 1809.7277425 (350)	total: 10.6s	remaining: 19.5s
400:	learn: 1762.9300386	test: 1800.8860436	best: 1800.8860436 (400)	total: 11.8s	remaining: 17.6s
450:	learn: 1750.7138791	test: 1794.0672023	best: 1794.0672023 (450)	total: 13.1s	remaining: 16s
500:	learn: 1740.1995900	test: 1787.8115510	best: 1787.8115510 (500)	total: 14.4s	remaining: 14.4s
550:	learn: 1729.2962339	test: 1781.0992495	best: 1781.0992495 (550)	total: 15.9s	remaining: 13s
600:	learn: 1720.1303292	test: 1776.1283027	best: 1776.1283027 (600)	total: 17.2s	remaining: 11.4s
650:	learn: 1711.5246010	test: 1771.1843744	best: 1771.1843744 (650)	total: 18.3s	remaining: 9.83s
700:	learn: 1704.0744129	test: 1766.7871303	best: 1766.7871303 (700)	total: 19.5s	remaining: 8.32s
750:	learn: 1695.9360785	test: 1762.4944974	best: 1762.4944974 (750)	total: 20.7s	remaining: 6.85s
800:	learn: 1689.3666869	test: 1758.9103840	best: 1758.9103840 (800)	total: 21.8s	remaining: 5.43s
850:	learn: 1683.0905769	test: 1756.3939395	best: 1756.3939395 (850)	total: 23.1s	remaining: 4.04s
900:	learn: 1675.8872881	test: 1752.7140787	best: 1752.7140787 (900)	total: 24.2s	remaining: 2.66s
950:	learn: 1669.3882887	test: 1749.8259847	best: 1749.8259847 (950)	total: 25.6s	remaining: 1.32s
999:	learn: 1663.0012284	test: 1746.3283688	best: 1746.3283688 (999)	total: 26.8s	remaining: 0us

bestTest = 1746.328369
bestIteration = 999

CPU times: user 1min 18s, sys: 4.36 s, total: 1min 22s
Wall time: 28.6 s

In [36]:
%%time

pred_train = model.predict(features_train)
pred_valid = model.predict(features_valid)
pred_test = model.predict(features_test)

CPU times: user 1.23 s, sys: 11.1 ms, total: 1.24 s
Wall time: 813 ms

In [37]:
print("Train RMSE:", rmse(target_train, pred_train).round(5))
print("Valid RMSE:", rmse(target_valid, pred_valid).round(5))
print("Test RMSE: ", rmse(target_test, pred_test).round(5))

Train RMSE: 1663.00123
Valid RMSE: 1746.32837
Test RMSE:  1734.82601

# 3. Model analysis

| Model | RMSE | Prediction time, с | Training time, with |
|----|----|-------|--------|
| Линейная регрессия | 3220 | 0.156 | 0.4 |
| LightGBM(1000) | 1640 | 8.47 | 12.9 |
| CatBoost(1000) | 1730 | 0.899 | 27.2 |


- The fastest (in training and prediction) model is linear regression. But the quality is low
- The model with the best quality is gradient boosting LightGBM with 1000 trees.
- The model with balanced prediction speed and quality is gradient boosting CatBoost with 1000 trees without category processing